import re
import os

filepath = r"D:\Igo-websites\Igo- Crop Care\lib\products-data.ts"
with open(filepath, "r", encoding="utf-8") as f:
    content = f.read()

replacements = {
    "'/products/chemica/urea.png'": "'/products/Products/Chemical%20Fertilizers/UREA.png'",
    "'/products/chemica/dap.png'": "'/products/Products/Chemical%20Fertilizers/DAP%20(Di-Ammonium%20Phosphate).png'",
    "'/products/chemica/ammonium-nitrate.png'": "'/products/Products/Chemical%20Fertilizers/Ammonium%20Nitrate.png'",
    "'/products/chemica/ammonium-sulphate.png'": "'/products/Products/Chemical%20Fertilizers/Ammonium%20Sulphate.png'",
    "'/products/chemica/calcium-ammonium-nitrate.png'": "'/products/Products/Chemical%20Fertilizers/Calcium%20Ammonium%20Nitrate%20(CAN).png'",
    "'/products/chemica/sodium-nitrate.png'": "'/products/Products/Chemical%20Fertilizers/Sodium%20Nitrate.png'",
    "'/products/chemica/bio-compost.png'": "'/products/Products/Organic%20Fertilizers/Bio%20Composer.png'",
    "'/products/chemica/coco-peat.png'": "'/products/Products/Organic%20Fertilizers/CoCo%20Peat.png'",
    "'/products/chemica/cow-dung-compost.png'": "'/products/Products/Organic%20Fertilizers/Cow%20Dung.png'",
    "'/products/chemica/kitchen-waste-compost.png'": "'/products/Products/Organic%20Fertilizers/Kitchen%20Waste%20Compost.png'",
    "'/products/chemica/leaf-compost.png'": "'/products/Products/Organic%20Fertilizers/Leaf%20Composer.png'",
    "'/products/chemica/paddy-seed.png'": "'/products/Products/Field%20Seeds/Paddy.png'",
    "'/products/chemica/wheat-seed.png'": "'/products/Products/Field%20Seeds/Wheat%20Seed.png'",
    "'/products/chemica/maize-seed.png'": "'/products/Products/Field%20Seeds/Maize%20Corn.png'",
    "'/products/chemica/groundnut-seed.png'": "'/products/Products/Field%20Seeds/Groundnut.png'",
    "'/products/chemica/watermelon-seed.png'": "'/products/Products/Fruit%20Seed/Watermelon%20seed.png'",
}

for old, new in replacements.items():
    content = content.replace(old, new)


fruit_additions = """  {
    id: 'ch-fs-002',
    name: 'Chemica Grapes Seeds',
    description: 'High quality grapes seeds for vigorous vine growth.',
    shortDesc: 'High quality grapes seeds',
    category: 'seeds',
    subCategory: 'fruit-plantation',
    price: 500,
    mrp: 600,
    discount: 10,
    image_url: '/products/Products/Fruit%20Seed/Grapes.png',
    rating: 4.5,
    reviews_count: 120,
    stock: 200,
    brand: 'Chemica',
    dosage: 'Standard',
    composition: 'Seeds',
    crops: ['Grapes'],
    isOrganic: true,
    tags: ['grapes', 'fruit', 'seeds'],
    aiImagePrompt: 'Chemica Grapes Seeds',
  },
  {
    id: 'ch-fs-003',
    name: 'Chemica Guava Seeds',
    description: 'High quality guava seeds for healthy fruit bearing.',
    shortDesc: 'High quality guava seeds',
    category: 'seeds',
    subCategory: 'fruit-plantation',
    price: 400,
    mrp: 500,
    discount: 10,
    image_url: '/products/Products/Fruit%20Seed/Guava.png',
    rating: 4.5,
    reviews_count: 110,
    stock: 200,
    brand: 'Chemica',
    dosage: 'Standard',
    composition: 'Seeds',
    crops: ['Guava'],
    isOrganic: true,
    tags: ['guava', 'fruit', 'seeds'],
    aiImagePrompt: 'Chemica Guava Seeds',
  },
  {
    id: 'ch-fs-004',
    name: 'Chemica MuskMelon Seeds',
    description: 'High quality muskmelon seeds for sweet and juicy harvest.',
    shortDesc: 'High quality muskmelon seeds',
    category: 'seeds',
    subCategory: 'fruit-plantation',
    price: 300,
    mrp: 400,
    discount: 10,
    image_url: '/products/Products/Fruit%20Seed/MuskMelon.png',
    rating: 4.6,
    reviews_count: 140,
    stock: 150,
    brand: 'Chemica',
    dosage: 'Standard',
    composition: 'Seeds',
    crops: ['MuskMelon'],
    isOrganic: true,
    tags: ['muskmelon', 'fruit', 'seeds'],
    aiImagePrompt: 'Chemica MuskMelon Seeds',
  },
  {
    id: 'ch-fs-005',
    name: 'Chemica Pomegranate Seeds',
    description: 'High quality pomegranate seeds for vibrant ruby fruits.',
    shortDesc: 'High quality pomegranate seeds',
    category: 'seeds',
    subCategory: 'fruit-plantation',
    price: 600,
    mrp: 750,
    discount: 10,
    image_url: '/products/Products/Fruit%20Seed/Pomegranate.png',
    rating: 4.8,
    reviews_count: 180,
    stock: 120,
    brand: 'Chemica',
    dosage: 'Standard',
    composition: 'Seeds',
    crops: ['Pomegranate'],
    isOrganic: true,
    tags: ['pomegranate', 'fruit', 'seeds'],
    aiImagePrompt: 'Chemica Pomegranate Seeds',
  }
];"""

content = content.replace("];", "];\n\n// TEMP_MARKER_FRUIT", 1) # Only replace the first one? No, wait. 

# Let's use regex to be safer
content = re.sub(r"(export const FRUIT_PLANTATION_SEEDS: ExtendedProduct\[\] = \[\s*\{.*?\}\s*),(\s*\];)", r"\1,\n" + fruit_additions.replace("];", "") + r"\2", content, flags=re.DOTALL)


veg_content = """export const VEGETABLE_SEEDS: ExtendedProduct[] = [
  {
    id: 'ch-v-001',
    name: 'Chemica Bitter Guard Seeds',
    description: 'High-yield bitter guard seeds.',
    shortDesc: 'High-yield bitter guard seeds',
    category: 'seeds',
    subCategory: 'vegetable',
    price: 150,
    mrp: 200,
    discount: 15,
    image_url: '/products/Products/Vegetables/Bitter%20Guard.png',
    rating: 4.5,
    reviews_count: 220,
    stock: 500,
    brand: 'Chemica',
    dosage: 'Standard',
    composition: 'Seeds',
    crops: ['Bitter Guard'],
    isOrganic: true,
    tags: ['vegetable', 'bitter guard', 'seeds'],
    aiImagePrompt: 'Chemica Bitter Guard Seeds',
  },
  {
    id: 'ch-v-002',
    name: 'Chemica Brinjal Seeds',
    description: 'High-yield brinjal seeds.',
    shortDesc: 'High-yield brinjal seeds',
    category: 'seeds',
    subCategory: 'vegetable',
    price: 120,
    mrp: 150,
    discount: 10,
    image_url: '/products/Products/Vegetables/Brinjal.png',
    rating: 4.4,
    reviews_count: 150,
    stock: 600,
    brand: 'Chemica',
    dosage: 'Standard',
    composition: 'Seeds',
    crops: ['Brinjal'],
    isOrganic: true,
    tags: ['vegetable', 'brinjal', 'seeds'],
    aiImagePrompt: 'Chemica Brinjal Seeds',
  },
  {
    id: 'ch-v-003',
    name: 'Chemica Cucumber Seeds',
    description: 'High-yield cucumber seeds.',
    shortDesc: 'High-yield cucumber seeds',
    category: 'seeds',
    subCategory: 'vegetable',
    price: 180,
    mrp: 220,
    discount: 12,
    image_url: '/products/Products/Vegetables/Cucumber.png',
    rating: 4.6,
    reviews_count: 310,
    stock: 450,
    brand: 'Chemica',
    dosage: 'Standard',
    composition: 'Seeds',
    crops: ['Cucumber'],
    isOrganic: true,
    tags: ['vegetable', 'cucumber', 'seeds'],
    aiImagePrompt: 'Chemica Cucumber Seeds',
  },
  {
    id: 'ch-v-004',
    name: 'Chemica Ladiesfinger Seeds',
    description: 'High-yield ladiesfinger seeds.',
    shortDesc: 'High-yield ladiesfinger seeds',
    category: 'seeds',
    subCategory: 'vegetable',
    price: 160,
    mrp: 200,
    discount: 10,
    image_url: '/products/Products/Vegetables/Ladiesfinger.png',
    rating: 4.5,
    reviews_count: 270,
    stock: 500,
    brand: 'Chemica',
    dosage: 'Standard',
    composition: 'Seeds',
    crops: ['Ladiesfinger'],
    isOrganic: true,
    tags: ['vegetable', 'ladiesfinger', 'seeds'],
    aiImagePrompt: 'Chemica Ladiesfinger Seeds',
  },
  {
    id: 'ch-v-005',
    name: 'Chemica Pumpkin Seeds',
    description: 'High-yield pumpkin seeds.',
    shortDesc: 'High-yield pumpkin seeds',
    category: 'seeds',
    subCategory: 'vegetable',
    price: 200,
    mrp: 250,
    discount: 15,
    image_url: '/products/Products/Vegetables/Pumpkin.png',
    rating: 4.7,
    reviews_count: 400,
    stock: 350,
    brand: 'Chemica',
    dosage: 'Standard',
    composition: 'Seeds',
    crops: ['Pumpkin'],
    isOrganic: true,
    tags: ['vegetable', 'pumpkin', 'seeds'],
    aiImagePrompt: 'Chemica Pumpkin Seeds',
  }
];"""

content = content.replace("export const VEGETABLE_SEEDS: ExtendedProduct[] = [];", veg_content)


flower_content = """export const FLOWER_HERBAL_SEEDS: ExtendedProduct[] = [
  {
    id: 'ch-fl-001',
    name: 'Chemica Calendula Seeds',
    description: 'Beautiful Calendula flower seeds.',
    shortDesc: 'Beautiful Calendula flower seeds',
    category: 'seeds',
    subCategory: 'flower-herbal',
    price: 80,
    mrp: 100,
    discount: 20,
    image_url: '/products/Products/Flowers/Calendula.png',
    rating: 4.8,
    reviews_count: 120,
    stock: 300,
    brand: 'Chemica',
    dosage: 'Standard',
    composition: 'Seeds',
    crops: ['Calendula'],
    isOrganic: true,
    tags: ['flower', 'calendula', 'seeds'],
    aiImagePrompt: 'Chemica Calendula Seeds',
  },
  {
    id: 'ch-fl-002',
    name: 'Chemica Dianthus Seeds',
    description: 'Beautiful Dianthus flower seeds.',
    shortDesc: 'Beautiful Dianthus flower seeds',
    category: 'seeds',
    subCategory: 'flower-herbal',
    price: 90,
    mrp: 120,
    discount: 15,
    image_url: '/products/Products/Flowers/Dianthus.png',
    rating: 4.6,
    reviews_count: 140,
    stock: 250,
    brand: 'Chemica',
    dosage: 'Standard',
    composition: 'Seeds',
    crops: ['Dianthus'],
    isOrganic: true,
    tags: ['flower', 'dianthus', 'seeds'],
    aiImagePrompt: 'Chemica Dianthus Seeds',
  },
  {
    id: 'ch-fl-003',
    name: 'Chemica Jasmine Seeds',
    description: 'Beautiful Jasmine flower seeds.',
    shortDesc: 'Beautiful Jasmine flower seeds',
    category: 'seeds',
    subCategory: 'flower-herbal',
    price: 150,
    mrp: 200,
    discount: 20,
    image_url: '/products/Products/Flowers/JAsmine.png',
    rating: 4.9,
    reviews_count: 320,
    stock: 400,
    brand: 'Chemica',
    dosage: 'Standard',
    composition: 'Seeds',
    crops: ['Jasmine'],
    isOrganic: true,
    tags: ['flower', 'jasmine', 'seeds'],
    aiImagePrompt: 'Chemica Jasmine Seeds',
  },
  {
    id: 'ch-fl-004',
    name: 'Chemica Sunflower Seeds',
    description: 'Beautiful Sunflower seeds.',
    shortDesc: 'Beautiful Sunflower seeds',
    category: 'seeds',
    subCategory: 'flower-herbal',
    price: 100,
    mrp: 130,
    discount: 10,
    image_url: '/products/Products/Flowers/Sunflower.png',
    rating: 4.7,
    reviews_count: 210,
    stock: 350,
    brand: 'Chemica',
    dosage: 'Standard',
    composition: 'Seeds',
    crops: ['Sunflower'],
    isOrganic: true,
    tags: ['flower', 'sunflower', 'seeds'],
    aiImagePrompt: 'Chemica Sunflower Seeds',
  }
];"""

content = content.replace("export const FLOWER_HERBAL_SEEDS: ExtendedProduct[] = [];", flower_content)

with open(filepath, "w", encoding="utf-8") as f:
    f.write(content)
print("Updated successfully")
