// lib/products-data.ts
// ─── Master Product Catalog ───────────────────────────────────────────────────
// This file defines the extended product catalog for IGO CropCare.
// It is separate from lib/supabase/db.ts (which handles DB logic).
// Used by: fertilizers page, seeds page, protein-cuts page, API routes.

export interface ExtendedProduct {
  id: string;
  name: string;
  description: string;
  shortDesc: string;
  category: string;
  subCategory: string;
  price: number;
  mrp: number;
  discount: number;
  image_url: string;
  rating: number;
  reviews_count: number;
  stock: number;
  brand: string;
  dosage: string;
  composition: string;
  crops: string[];
  badge?: string;
  isOrganic: boolean;
  tags: string[];
  aiImagePrompt: string;
}

// ─── FERTILIZERS ─────────────────────────────────────────────────────────────

export const ORGANIC_FERTILIZERS: ExtendedProduct[] = [
  {
    id: 'org-001',
    name: 'Vermicompost Premium 5kg',
    description: 'Enriched vermicompost made from earthworm castings. Rich in humus, beneficial microbes, enzymes and plant growth hormones. Improves soil structure, water retention and aeration. Enhances root development and microbial activity.',
    shortDesc: 'Premium earthworm castings — enriches soil naturally',
    category: 'fertilizers',
    subCategory: 'organic',
    price: 299,
    mrp: 399,
    discount: 25,
    image_url: '/products/fertilizer_npk.png',
    rating: 4.8,
    reviews_count: 1456,
    stock: 250,
    brand: 'Multiplex',
    dosage: '2–3 kg per plant or 5 tonnes per acre',
    composition: 'Vermicompost (worm castings) 100%',
    crops: ['Tomato', 'Chilli', 'Paddy', 'Wheat', 'Vegetables', 'Fruits'],
    badge: '🌿 Organic',
    isOrganic: true,
    tags: ['organic', 'soil-health', 'compost'],
    aiImagePrompt: 'Premium vermicompost fertilizer bag, 5kg brown kraft paper packaging, IGO CropCare brand label, green leaf logo, white studio background, soft shadow, ecommerce product photography, 4K sharp',
  },
  {
    id: 'org-002',
    name: 'Neem Cake Fertilizer 10kg',
    description: 'Organic neem seed cake — natural pesticide and fertilizer. Controls soil-borne pests and nematodes. Slow-release nitrogen source. Inhibits nitrification, reducing nitrogen loss. Safe for all crops, excellent for soil health.',
    shortDesc: 'Dual action — fertilizes & controls soil pests',
    category: 'fertilizers',
    subCategory: 'organic',
    price: 349,
    mrp: 499,
    discount: 30,
    image_url: '/products/seeds_tomato.png',
    rating: 4.7,
    reviews_count: 892,
    stock: 180,
    brand: 'Katyayani',
    dosage: '250–300 kg per acre as basal application',
    composition: 'Neem seed cake 100%, NPK: 5:1:1.5',
    crops: ['Paddy', 'Sugarcane', 'Cotton', 'Vegetables', 'Fruit crops'],
    badge: '🌿 Organic',
    isOrganic: true,
    tags: ['organic', 'nematicide', 'slow-release'],
    aiImagePrompt: 'Neem cake organic fertilizer, 10kg woven polypropylene bag, yellow-green label with neem leaf imagery, white background, product photography lighting, premium agricultural packaging',
  },
  {
    id: 'org-003',
    name: 'Humic Acid + Fulvic Acid 98% — 1kg',
    description: 'Concentrated leonardite-derived humic and fulvic acid. Dramatically improves nutrient uptake efficiency. Stimulates root development and microbial population. Enhances stress tolerance and yield quality. Activates soil minerals for plant absorption.',
    shortDesc: 'Supercharge nutrient uptake with 98% concentrated formula',
    category: 'fertilizers',
    subCategory: 'organic',
    price: 599,
    mrp: 899,
    discount: 33,
    image_url: '/products/fertilizer_npk.png',
    rating: 4.9,
    reviews_count: 2145,
    stock: 120,
    brand: 'Katyayani',
    dosage: '1–2 kg per acre soil application; 0.5g/L foliar',
    composition: 'Humic Acid 80% + Fulvic Acid 18%',
    crops: ['All crops'],
    badge: '⭐ Best Seller',
    isOrganic: true,
    tags: ['humic-acid', 'soil-conditioner', 'growth-booster'],
    aiImagePrompt: 'Humic acid fulvic acid fertilizer 1kg black powder in premium metallic silver pouch, nutrition facts label, white studio backdrop, ecommerce product shot, macro detail of product',
  },
  {
    id: 'org-004',
    name: 'Seaweed Extract Liquid — 500ml',
    description: 'Ascophyllum nodosum seaweed extract — rich in natural cytokinins, auxins, gibberellins and betaines. Boosts flowering, fruit set, and crop quality. Enhances tolerance to drought, frost, and salinity stress.',
    shortDesc: 'Ocean-sourced growth booster for stress tolerance',
    category: 'fertilizers',
    subCategory: 'organic',
    price: 358,
    mrp: 490,
    discount: 27,
    image_url: '/products/fertilizer_npk.png',
    rating: 4.7,
    reviews_count: 687,
    stock: 95,
    brand: 'PI Industries',
    dosage: '2–3 ml per liter foliar spray; 1L per acre drip',
    composition: 'Seaweed extract (Ascophyllum nodosum) 15% w/v',
    crops: ['Vegetables', 'Fruits', 'Cotton', 'Paddy'],
    isOrganic: true,
    tags: ['seaweed', 'growth-promoter', 'stress-tolerance'],
    aiImagePrompt: 'Seaweed extract liquid fertilizer 500ml dark green glass bottle with premium label, ocean blue color scheme, white backdrop, product photography',
  },
  {
    id: 'org-005',
    name: 'Panchagavya Organic Liquid — 1L',
    description: 'Traditional Vedic preparation from 5 cow-derived products: milk, curd, ghee, cow urine, cow dung. Rich in growth hormones, vitamins, macro and micro nutrients. Improves soil life and plant immunity naturally.',
    shortDesc: 'Vedic organic growth promoter from 5 cow products',
    category: 'fertilizers',
    subCategory: 'organic',
    price: 249,
    mrp: 349,
    discount: 29,
    image_url: '/products/fertilizer_npk.png',
    rating: 4.5,
    reviews_count: 345,
    stock: 75,
    brand: 'Gomata',
    dosage: '3% solution (30ml/L) foliar spray or soil drench',
    composition: 'Cow milk, curd, ghee, urine, dung (panchagavya)',
    crops: ['All organic crops', 'Paddy', 'Sugarcane', 'Vegetables'],
    isOrganic: true,
    tags: ['panchagavya', 'vedic', 'organic-farming'],
    aiImagePrompt: 'Panchagavya organic liquid fertilizer 1 litre amber bottle traditional Indian style label with cow and leaf imagery, natural earthy tones, white background, ecommerce photography',
  },
];

export const CHEMICAL_FERTILIZERS: ExtendedProduct[] = [
  {
    id: 'chem-001',
    name: 'Urea 46% N — 50kg Bag',
    description: 'Highest nitrogen content among solid fertilizers at 46% N. Fast-acting source of nitrogen for all crops. Ideal for top-dressing application. Promotes vigorous vegetative growth and deep green color. Most widely used fertilizer in India.',
    shortDesc: 'India\'s most-used nitrogen fertilizer — 46% N',
    category: 'fertilizers',
    subCategory: 'chemical',
    price: 280,
    mrp: 310,
    discount: 10,
    image_url: '/products/fertilizer_npk.png',
    rating: 4.5,
    reviews_count: 3245,
    stock: 500,
    brand: 'IFFCO',
    dosage: '50–100 kg per acre based on crop requirement',
    composition: 'Nitrogen 46% as Urea',
    crops: ['Paddy', 'Wheat', 'Maize', 'Sugarcane', 'Cotton', 'All crops'],
    badge: '💊 Essential',
    isOrganic: false,
    tags: ['nitrogen', 'urea', 'top-dressing'],
    aiImagePrompt: 'Urea 46% nitrogen fertilizer 50kg white woven polypropylene bag IFFCO brand, Indian agricultural packaging, white studio background, product photography',
  },
  {
    id: 'chem-002',
    name: 'DAP (Di-Ammonium Phosphate) — 50kg',
    description: 'Highly concentrated phosphorus and nitrogen fertilizer. Provides both N (18%) and P2O5 (46%). Essential for root development, flowering, and seed formation. Most effective when applied at sowing or planting time as basal dose.',
    shortDesc: 'High-phosphorus basal fertilizer for strong roots',
    category: 'fertilizers',
    subCategory: 'chemical',
    price: 1350,
    mrp: 1450,
    discount: 7,
    image_url: '/products/seeds_tomato.png',
    rating: 4.8,
    reviews_count: 2890,
    stock: 400,
    brand: 'IFFCO',
    dosage: '50–75 kg per acre as basal dose',
    composition: 'N 18% + P2O5 46%',
    crops: ['Paddy', 'Wheat', 'Pulses', 'Oilseeds', 'Vegetables'],
    badge: '🌱 Basal Essential',
    isOrganic: false,
    tags: ['DAP', 'phosphorus', 'basal', 'root-growth'],
    aiImagePrompt: 'DAP Di-Ammonium Phosphate fertilizer 50kg grey bag IFFCO brand Indian agricultural product, white background, ecommerce style photography',
  },
  {
    id: 'chem-003',
    name: 'NPK 19:19:19 Water Soluble — 1kg',
    description: 'Perfectly balanced water-soluble NPK fertilizer. Equal ratio of all three major nutrients for uniform crop nutrition. Instantly dissolves for foliar spray or fertigation through drip. Boosted with micronutrients Zinc, Boron, and Molybdenum.',
    shortDesc: 'Balanced NPK — perfect for foliar & drip feeding',
    category: 'fertilizers',
    subCategory: 'chemical',
    price: 349,
    mrp: 499,
    discount: 30,
    image_url: '/products/fertilizer_npk.png',
    rating: 4.9,
    reviews_count: 3218,
    stock: 350,
    brand: 'Katyayani',
    dosage: '3–5 g/L foliar; 2–4 kg/acre fertigation',
    composition: 'N 19% + P2O5 19% + K2O 19% + Micronutrients',
    crops: ['All crops — universal'],
    badge: '⭐ Top Rated',
    isOrganic: false,
    tags: ['NPK', 'water-soluble', 'balanced', 'foliar'],
    aiImagePrompt: 'NPK 19:19:19 water soluble fertilizer 1kg white crystalline powder in premium resealable pouch with bold green label, white background, ecommerce product photography',
  },
  {
    id: 'chem-004',
    name: 'MOP (Muriate of Potash) — 50kg',
    description: 'Concentrated potassium source at 60% K2O. Strengthens plant cell walls and stems. Improves drought and disease resistance. Essential for high-value crops, fruits and vegetables. Enhances fruit quality, taste, and shelf life.',
    shortDesc: 'High-potassium fertilizer for fruit quality & strength',
    category: 'fertilizers',
    subCategory: 'chemical',
    price: 1100,
    mrp: 1250,
    discount: 12,
    image_url: '/products/fungicide_copper.png',
    rating: 4.6,
    reviews_count: 1234,
    stock: 280,
    brand: 'IPL',
    dosage: '25–50 kg per acre',
    composition: 'K2O 60%',
    crops: ['Potato', 'Banana', 'Sugarcane', 'Cotton', 'Vegetables'],
    isOrganic: false,
    tags: ['potassium', 'MOP', 'fruit-quality'],
    aiImagePrompt: 'MOP Muriate of Potash fertilizer 50kg red-pink granules in white plastic bag, product label, white studio background, agricultural product photography',
  },
  {
    id: 'chem-005',
    name: 'SSP Single Super Phosphate — 50kg',
    description: 'Phosphatic fertilizer containing 16% P2O5, 11% Sulphur, and 21% Calcium. Triple nutrient source in one bag. Sulphur improves protein content and oil content in oilseed crops. Best for alkaline soils where sulphur deficiency is common.',
    shortDesc: 'Triple nutrient — P, S, Ca — ideal for oilseeds',
    category: 'fertilizers',
    subCategory: 'chemical',
    price: 480,
    mrp: 550,
    discount: 13,
    image_url: '/products/seeds_tomato.png',
    rating: 4.4,
    reviews_count: 876,
    stock: 320,
    brand: 'GSFC',
    dosage: '100–150 kg per acre as basal',
    composition: 'P2O5 16% + S 11% + Ca 21%',
    crops: ['Groundnut', 'Soybean', 'Sunflower', 'Pulses', 'Wheat'],
    isOrganic: false,
    tags: ['SSP', 'phosphorus', 'sulphur', 'oilseeds'],
    aiImagePrompt: 'SSP Single Super Phosphate fertilizer 50kg grey granular powder bag, agricultural label, white background, product photography',
  },
];

export const BIO_FERTILIZERS: ExtendedProduct[] = [
  {
    id: 'bio-001',
    name: 'Azospirillum Biofertilizer — 1kg',
    description: 'Nitrogen-fixing bacteria for non-legume crops. Fixes atmospheric nitrogen and produces growth hormones (IAA, GA). Saves 20–30 kg chemical nitrogen per acre. Compatible with seed treatment and soil application.',
    shortDesc: 'Nitrogen-fixing bacteria — reduce urea by 25%',
    category: 'fertilizers',
    subCategory: 'biofertilizer',
    price: 180,
    mrp: 250,
    discount: 28,
    image_url: '/products/seeds_tomato.png',
    rating: 4.6,
    reviews_count: 789,
    stock: 150,
    brand: 'Multiplex',
    dosage: '200g seed treatment or 2 kg/acre soil application',
    composition: 'Azospirillum brasilense (2x10^8 CFU/g)',
    crops: ['Paddy', 'Wheat', 'Maize', 'Sugarcane', 'Millets'],
    isOrganic: true,
    tags: ['biofertilizer', 'nitrogen-fixing', 'azospirillum'],
    aiImagePrompt: 'Azospirillum biofertilizer 1kg white powder packet with microbiology illustration, green eco label, white background, ecommerce product photography',
  },
  {
    id: 'bio-002',
    name: 'Rhizobium Biofertilizer — 1kg',
    description: 'Root nodule bacteria for leguminous crops. Fixes 50–100 kg nitrogen per acre through symbiosis with legume roots. Dramatically reduces nitrogen fertilizer requirement. Improves soil fertility for subsequent crops.',
    shortDesc: 'Legume nitrogen-fixer — saves 50–100kg N/acre',
    category: 'fertilizers',
    subCategory: 'biofertilizer',
    price: 175,
    mrp: 249,
    discount: 30,
    image_url: '/products/fertilizer_npk.png',
    rating: 4.7,
    reviews_count: 654,
    stock: 130,
    brand: 'Multiplex',
    dosage: '200g per 10 kg seed treatment',
    composition: 'Rhizobium sp. (2x10^8 CFU/g)',
    crops: ['Soybean', 'Groundnut', 'Chickpea', 'Moong', 'All pulses'],
    isOrganic: true,
    tags: ['biofertilizer', 'rhizobium', 'pulses', 'nitrogen'],
    aiImagePrompt: 'Rhizobium biofertilizer 1kg brown powder in white sealed packet, scientific label with root nodule diagram, white background, product photography',
  },
  {
    id: 'bio-003',
    name: 'PSB (Phosphate Solubilizing Bacteria) — 1kg',
    description: 'Converts insoluble phosphates in soil into plant-available form. Enhances P uptake by 30–50%. Reduces chemical phosphorus fertilizer requirement. Synergistic effect when used with DAP or SSP.',
    shortDesc: 'Unlock soil phosphorus — 30–50% better P-uptake',
    category: 'fertilizers',
    subCategory: 'biofertilizer',
    price: 180,
    mrp: 249,
    discount: 28,
    image_url: '/products/fertilizer_npk.png',
    rating: 4.5,
    reviews_count: 543,
    stock: 110,
    brand: 'Multiplex',
    dosage: '2 kg per acre soil application with compost',
    composition: 'Bacillus megaterium (2x10^8 CFU/g)',
    crops: ['All crops'],
    isOrganic: true,
    tags: ['biofertilizer', 'PSB', 'phosphorus-solubilizing'],
    aiImagePrompt: 'PSB Phosphate Solubilizing Bacteria biofertilizer packet 1kg blue-green label, white background, ecommerce agricultural product photo',
  },
  {
    id: 'bio-004',
    name: 'Mycorrhiza (VAM) Biofertilizer — 1kg',
    description: 'Vesicular Arbuscular Mycorrhiza — extends root network up to 700 times. Dramatically improves water and phosphorus absorption. Increases drought resistance. Compatible with all crops. Reduces transplant shock in nursery seedlings.',
    shortDesc: 'Extend roots 700x — drought-proof your crops',
    category: 'fertilizers',
    subCategory: 'biofertilizer',
    price: 399,
    mrp: 599,
    discount: 33,
    image_url: '/products/seeds_tomato.png',
    rating: 4.8,
    reviews_count: 876,
    stock: 90,
    brand: 'Tapas',
    dosage: '5g per plant or 5 kg per acre soil mix',
    composition: 'Glomus intraradices (100 spores/g)',
    crops: ['Vegetables', 'Fruits', 'Field crops', 'Plantation'],
    badge: '🔬 Biotechnology',
    isOrganic: true,
    tags: ['mycorrhiza', 'VAM', 'root-health', 'drought-tolerance'],
    aiImagePrompt: 'Mycorrhiza VAM biofertilizer 1kg premium silver pouch with mushroom root illustration, scientific ecolabel, white background, macro detail shot',
  },
  {
    id: 'bio-005',
    name: 'Trichoderma Viride Bio-Fungicide — 1kg',
    description: 'Beneficial fungus that controls soil-borne pathogens like Fusarium, Pythium, Rhizoctonia. Produces enzymes that break down fungal cell walls. Promotes root growth via phosphate solubilization. Dual action: disease control + growth promotion.',
    shortDesc: 'Bio-control soil diseases + boost root growth',
    category: 'fertilizers',
    subCategory: 'biofertilizer',
    price: 220,
    mrp: 320,
    discount: 31,
    image_url: '/products/fungicide_copper.png',
    rating: 4.6,
    reviews_count: 432,
    stock: 140,
    brand: 'Multiplex',
    dosage: '2 kg/acre soil mix; 10g/L for seed treatment',
    composition: 'Trichoderma viride (2x10^8 CFU/g)',
    crops: ['Vegetables', 'Chilli', 'Tomato', 'Cotton', 'All crops'],
    isOrganic: true,
    tags: ['trichoderma', 'bio-control', 'soil-borne-disease'],
    aiImagePrompt: 'Trichoderma Viride biofungicide 1kg green powder bag, bio-organic label with microscope image, white background, ecommerce product shot',
  },
];

export const MICRONUTRIENT_FERTILIZERS: ExtendedProduct[] = [
  {
    id: 'micro-001',
    name: 'Zinc Sulphate 21% — 5kg',
    description: 'Zinc deficiency corrector — most common micronutrient deficiency in Indian soils. Treats khaira disease in paddy, white bud in maize. Essential for chlorophyll formation, enzyme activation, and auxin synthesis.',
    shortDesc: 'Cure zinc deficiency — khaira in paddy, white bud in maize',
    category: 'fertilizers',
    subCategory: 'micronutrient',
    price: 320,
    mrp: 420,
    discount: 24,
    image_url: '/products/fungicide_copper.png',
    rating: 4.7,
    reviews_count: 1678,
    stock: 220,
    brand: 'Coromandel',
    dosage: '10–15 kg/acre soil; 0.5% foliar spray',
    composition: 'Zinc as ZnSO4·7H2O, Zn 21%',
    crops: ['Paddy', 'Wheat', 'Maize', 'Vegetables'],
    isOrganic: false,
    tags: ['zinc', 'micronutrient', 'deficiency-cure'],
    aiImagePrompt: 'Zinc Sulphate fertilizer 5kg white crystalline granules in resealable clear pouch with blue label, ecommerce product photography, white background',
  },
  {
    id: 'micro-002',
    name: 'Magnesium Sulphate (Epsom Salt) — 5kg',
    description: 'Magnesium and sulphur source for chlorophyll production. Cures interveinal chlorosis — yellowing between leaf veins. Activates phosphorus and nitrogen uptake. Essential for oil synthesis in oilseed crops.',
    shortDesc: 'Cure yellowing leaves — magnesium & sulphur combined',
    category: 'fertilizers',
    subCategory: 'micronutrient',
    price: 289,
    mrp: 390,
    discount: 26,
    image_url: '/products/seeds_tomato.png',
    rating: 4.6,
    reviews_count: 987,
    stock: 195,
    brand: 'Coromandel',
    dosage: '10 kg/acre soil or 1–2% foliar spray',
    composition: 'Mg 9.6% + S 12.9% as MgSO4·7H2O',
    crops: ['Tomato', 'Chilli', 'Potato', 'Oilseeds', 'All crops'],
    isOrganic: false,
    tags: ['magnesium', 'sulphur', 'chlorophyll', 'epsom'],
    aiImagePrompt: 'Magnesium Sulphate epsom salt fertilizer 5kg white crystalline in clear zipper bag, agricultural label, white studio background, product photography',
  },
  {
    id: 'micro-003',
    name: 'Multi-Micronutrient Mix (Chelated) — 500g',
    description: 'Complete chelated micronutrient mixture: Zinc, Iron, Manganese, Copper, Boron, Molybdenum. EDTA-chelated for maximum absorption through foliar spray. Corrects multiple micronutrient deficiencies simultaneously.',
    shortDesc: 'Complete chelated micronutrient — all deficiencies in one spray',
    category: 'fertilizers',
    subCategory: 'micronutrient',
    price: 199,
    mrp: 280,
    discount: 29,
    image_url: '/products/fertilizer_npk.png',
    rating: 4.7,
    reviews_count: 1234,
    stock: 165,
    brand: 'Dhanuka',
    dosage: '1.5–2.5 g per liter of water for foliar spray',
    composition: 'Zn 4% + Fe 3% + Mn 2% + Cu 1% + B 0.5% + Mo 0.05%',
    crops: ['All crops — universal'],
    badge: '⚗️ Chelated',
    isOrganic: false,
    tags: ['micronutrient', 'chelated', 'multi-nutrient'],
    aiImagePrompt: 'Chelated micronutrient mix 500g premium metallic silver pouch with colorful scientific nutrient chart, white background, ecommerce product photography',
  },
];

export const NANO_FERTILIZERS: ExtendedProduct[] = [
  {
    id: 'nano-001',
    name: 'Nano Urea Liquid — 500ml',
    description: 'Revolutionary IFFCO nano technology — urea in nano form (20–50nm particles). Each bottle replaces one bag of conventional urea. 85% nutrient use efficiency vs 30% of conventional. Foliar application — no soil application needed. Reduces groundwater pollution dramatically.',
    shortDesc: '1 bottle = 1 urea bag — revolutionary nano technology',
    category: 'fertilizers',
    subCategory: 'nano',
    price: 240,
    mrp: 280,
    discount: 14,
    image_url: '/products/fertilizer_npk.png',
    rating: 4.8,
    reviews_count: 2456,
    stock: 300,
    brand: 'IFFCO',
    dosage: '2–4 ml per liter water, foliar spray',
    composition: 'Nitrogen 4% in nano form (20–50nm)',
    crops: ['Paddy', 'Wheat', 'Sugarcane', 'Vegetables', 'All crops'],
    badge: '🔬 Nano Tech',
    isOrganic: false,
    tags: ['nano', 'urea', 'foliar', 'IFFCO', 'innovation'],
    aiImagePrompt: 'IFFCO Nano Urea liquid 500ml blue premium bottle with nano technology illustration, futuristic blue label design, white background, product photography, 4K',
  },
  {
    id: 'nano-002',
    name: 'Nano DAP Liquid — 500ml',
    description: 'Nano Di-Ammonium Phosphate — phosphorus in nano form. 10x better phosphorus use efficiency than conventional DAP. Penetrates leaf surface directly through stomata. Treats phosphorus deficiency without soil application. IFFCO approved technology.',
    shortDesc: '1 bottle = 1 DAP bag — nano phosphorus revolution',
    category: 'fertilizers',
    subCategory: 'nano',
    price: 600,
    mrp: 700,
    discount: 14,
    image_url: '/products/fertilizer_npk.png',
    rating: 4.7,
    reviews_count: 1876,
    stock: 220,
    brand: 'IFFCO',
    dosage: '2–4 ml per liter water, foliar spray',
    composition: 'N 8% + P2O5 16% in nano form',
    crops: ['All crops — universal'],
    badge: '🔬 Nano Tech',
    isOrganic: false,
    tags: ['nano', 'DAP', 'phosphorus', 'IFFCO'],
    aiImagePrompt: 'IFFCO Nano DAP liquid 500ml premium blue-green bottle, nano technology label, futuristic design, ecommerce white background, premium product photography',
  },
];

export const PGR_FERTILIZERS: ExtendedProduct[] = [
  {
    id: 'pgr-001',
    name: 'Gibberellic Acid 0.001% (GA3) — 1L',
    description: 'Plant growth regulator promoting cell elongation, germination, flowering, and fruit set. Breaks dormancy in seeds. Increases internode length for better light interception. Improves fruit size and uniformity in grapes and citrus.',
    shortDesc: 'Boost fruit size & break seed dormancy',
    category: 'fertilizers',
    subCategory: 'pgr',
    price: 380,
    mrp: 520,
    discount: 27,
    image_url: '/products/seeds_tomato.png',
    rating: 4.6,
    reviews_count: 567,
    stock: 85,
    brand: 'Coromandel',
    dosage: '1 ml per liter spray at flowering stage',
    composition: 'Gibberellic Acid (GA3) 0.001%',
    crops: ['Grapes', 'Mango', 'Tomato', 'Wheat', 'Paddy'],
    isOrganic: false,
    tags: ['PGR', 'gibberellin', 'fruit-size', 'flowering'],
    aiImagePrompt: 'Gibberellic Acid GA3 plant growth regulator 1 liter amber glass bottle with scientific label, white studio background, professional ecommerce photography',
  },
  {
    id: 'pgr-002',
    name: 'Amino Acid 50% + Seaweed Combo — 1L',
    description: 'Synergistic combination of hydrolyzed amino acids (plant-derived) and seaweed extract. Amino acids act as chelating agents improving micronutrient uptake. Seaweed cytokinins delay leaf senescence. Improves photosynthesis rate by 20–30%.',
    shortDesc: 'Amino + seaweed synergy — 30% more photosynthesis',
    category: 'fertilizers',
    subCategory: 'pgr',
    price: 499,
    mrp: 699,
    discount: 29,
    image_url: '/products/fertilizer_npk.png',
    rating: 4.8,
    reviews_count: 892,
    stock: 110,
    brand: 'Coromandel',
    dosage: '2–3 ml per liter foliar spray',
    composition: 'Amino Acid 50% + Seaweed Extract 5%',
    crops: ['Vegetables', 'Fruits', 'Flowers', 'All crops'],
    isOrganic: true,
    tags: ['amino-acid', 'seaweed', 'growth-booster'],
    aiImagePrompt: 'Amino acid seaweed fertilizer combo 1 liter dark green bottle with premium label, natural ingredients illustration, white background, ecommerce photography',
  },
];

// ─── SEEDS ───────────────────────────────────────────────────────────────────

export const FIELD_CROP_SEEDS: ExtendedProduct[] = [
  {
    id: 'seed-fc-001',
    name: 'Paddy IR-64 Long Grain Seeds — 5kg',
    description: 'IR-64 semi-dwarf, high-yielding paddy variety. Matures in 110–115 days. Resistant to blast and bacterial blight. Yield: 5–6 tonnes per hectare. Excellent grain quality with long slender grains. Performs well in kharif and rabi seasons.',
    shortDesc: 'High-yield long-grain paddy — 5–6 t/ha',
    category: 'seeds',
    subCategory: 'field-crops',
    price: 399,
    mrp: 550,
    discount: 27,
    image_url: '/products/seeds_tomato.png',
    rating: 4.7,
    reviews_count: 2345,
    stock: 200,
    brand: 'Syngenta',
    dosage: '20–25 kg seed per acre (transplanted)',
    composition: 'IR-64 O. sativa variety, germination >85%',
    crops: ['Paddy'],
    badge: '🌾 High Yield',
    isOrganic: false,
    tags: ['paddy', 'rice', 'IR-64', 'kharif', 'field-crop'],
    aiImagePrompt: 'Paddy IR-64 rice seeds 5kg packaging, golden paddy illustration, premium agricultural seed packet, white background, ecommerce product photography',
  },
  {
    id: 'seed-fc-002',
    name: 'Wheat HD-2967 — 10kg',
    description: 'HD-2967 semi-dwarf wheat variety. Tolerant to rust, powdery mildew. Matures in 140–150 days. Yield potential: 4.5–5.5 t/ha. High protein content for quality flour. Suitable for irrigated conditions in north India.',
    shortDesc: 'Premium wheat — disease-tolerant, 4.5–5.5 t/ha',
    category: 'seeds',
    subCategory: 'field-crops',
    price: 549,
    mrp: 699,
    discount: 21,
    image_url: '/products/seeds_tomato.png',
    rating: 4.6,
    reviews_count: 1678,
    stock: 180,
    brand: 'IARI',
    dosage: '100 kg per hectare',
    composition: 'Triticum aestivum HD-2967, germination >90%',
    crops: ['Wheat'],
    isOrganic: false,
    tags: ['wheat', 'rabi', 'HD-2967', 'field-crop'],
    aiImagePrompt: 'Wheat HD-2967 seeds 10kg packaging, golden wheat stalks illustration, agricultural seed packet, white background, ecommerce product shot',
  },
  {
    id: 'seed-fc-003',
    name: 'Maize Pioneer 30V92 Hybrid — 5kg',
    description: 'Pioneer 30V92 single cross hybrid maize. Maturity: 105–110 days. Excellent standability against lodging. Disease-tolerant (turcicum leaf blight, banded leaf). Yield: 8–10 tonnes per hectare. Suitable for kharif and spring seasons.',
    shortDesc: 'Pioneer hybrid maize — 8–10 t/ha, anti-lodging',
    category: 'seeds',
    subCategory: 'field-crops',
    price: 1299,
    mrp: 1599,
    discount: 19,
    image_url: '/products/seeds_tomato.png',
    rating: 4.8,
    reviews_count: 1234,
    stock: 120,
    brand: 'Pioneer (Corteva)',
    dosage: '8–10 kg per acre',
    composition: 'Zea mays hybrid 30V92, germination >90%',
    crops: ['Maize'],
    badge: '🌽 Pioneer Brand',
    isOrganic: false,
    tags: ['maize', 'corn', 'pioneer', 'hybrid', 'kharif'],
    aiImagePrompt: 'Pioneer hybrid maize seeds 5kg bright yellow packaging with corn illustration, Pioneer brand label, white background, ecommerce product photography',
  },
  {
    id: 'seed-fc-004',
    name: 'Cotton Bollgard-II BT Hybrid — 450g',
    description: 'Bollgard II double-stacked BT cotton with dual insect protection genes (Cry1Ac + Cry2Ab). Controls American bollworm, spotted bollworm, and pink bollworm. High ginning outturn (GOT) >38%. Suitable for peninsular India.',
    shortDesc: 'Bt-cotton — dual bollworm protection, high GOT',
    category: 'seeds',
    subCategory: 'field-crops',
    price: 799,
    mrp: 999,
    discount: 20,
    image_url: '/products/seeds_tomato.png',
    rating: 4.7,
    reviews_count: 987,
    stock: 150,
    brand: 'Mahyco',
    dosage: '1 packet (450g) per acre',
    composition: 'Gossypium hirsutum BG-II, germination >85%',
    crops: ['Cotton'],
    badge: '🧵 BT Hybrid',
    isOrganic: false,
    tags: ['cotton', 'BT', 'bollgard', 'insect-resistant'],
    aiImagePrompt: 'BT Cotton Bollgard II seeds 450g white vacuum sealed packet with cotton boll illustration, Mahyco brand, white background, product photography',
  },
  {
    id: 'seed-fc-005',
    name: 'Groundnut TMV-7 — 30kg',
    description: 'TMV-7 Valencia type groundnut variety. Early maturing (105 days). High oil content (50–52%). Drought tolerant. Resistant to early and late leaf spot. Yield: 1.8–2.5 tonnes pods per acre.',
    shortDesc: 'High-oil groundnut — 50–52% oil, drought tolerant',
    category: 'seeds',
    subCategory: 'field-crops',
    price: 1899,
    mrp: 2200,
    discount: 14,
    image_url: '/products/seeds_tomato.png',
    rating: 4.5,
    reviews_count: 678,
    stock: 90,
    brand: 'TNAU',
    dosage: '60–70 kg pods per acre (shelled)',
    composition: 'Arachis hypogaea TMV-7, germination >80%',
    crops: ['Groundnut'],
    isOrganic: false,
    tags: ['groundnut', 'peanut', 'oilseed', 'TMV-7'],
    aiImagePrompt: 'Groundnut TMV-7 seeds 30kg woven sack with groundnut plant illustration, agricultural label, white background, product photography',
  },
];

export const VEGETABLE_SEEDS: ExtendedProduct[] = [
  {
    id: 'seed-veg-001',
    name: 'Tomato Saaho F1 Hybrid — 10g',
    description: 'Syngenta Saaho — high-yield processing tomato variety. Deep red, firm fruits. TYLCV tolerant (Tomato Yellow Leaf Curl Virus). Maturity: 60–65 days. Yield: 35–40 t/ha. Round, uniform fruits ideal for export and processing.',
    shortDesc: 'TYLCV-tolerant tomato — 35–40 t/ha, export quality',
    category: 'seeds',
    subCategory: 'vegetable',
    price: 1199,
    mrp: 1525,
    discount: 21,
    image_url: '/products/seeds_tomato.png',
    rating: 4.8,
    reviews_count: 2890,
    stock: 200,
    brand: 'Syngenta',
    dosage: '100–150g seed per acre (nursery sowing)',
    composition: 'Lycopersicum esculentum F1 hybrid SAAHO',
    crops: ['Tomato'],
    badge: '🍅 Best Seller',
    isOrganic: false,
    tags: ['tomato', 'F1-hybrid', 'TYLCV-tolerant', 'syngenta'],
    aiImagePrompt: 'Syngenta Saaho tomato seeds 10g premium foil packet with vivid red tomato photography, green Syngenta branding, white background, ecommerce product photo',
  },
  {
    id: 'seed-veg-002',
    name: 'Chilli NS-1701 F1 Hybrid — 10g',
    description: 'Heavy-yielding green chilli hybrid. Long, glossy green fruits. Tolerance to thrips and mites. Maturity: 55–60 days. Yield: 25–30 t/ha. Good pungency (medium-hot). Excellent shelf life for distant marketing.',
    shortDesc: 'Prolific chilli hybrid — thrips tolerant, 25–30 t/ha',
    category: 'seeds',
    subCategory: 'vegetable',
    price: 799,
    mrp: 999,
    discount: 20,
    image_url: '/products/seeds_tomato.png',
    rating: 4.7,
    reviews_count: 1654,
    stock: 175,
    brand: 'Namdhari',
    dosage: '100g seed per acre',
    composition: 'Capsicum annuum F1 hybrid NS-1701',
    crops: ['Chilli'],
    isOrganic: false,
    tags: ['chilli', 'pepper', 'F1-hybrid', 'vegetable'],
    aiImagePrompt: 'Chilli seeds 10g premium seed packet with bright red-green chilli photography, agricultural brand label, white background, ecommerce product photography',
  },
  {
    id: 'seed-veg-003',
    name: 'Brinjal Namdhari Vajra F1 — 10g',
    description: 'Long purple brinjal hybrid with high yield. Smooth glossy skin, uniform color. Tolerant to bacterial wilt and LYMV. Maturity: 45–55 days. Continuous bearing. Yield: 30–40 t/ha. Popular in South India markets.',
    shortDesc: 'Long purple brinjal — continuous bearing, 30–40 t/ha',
    category: 'seeds',
    subCategory: 'vegetable',
    price: 899,
    mrp: 1099,
    discount: 18,
    image_url: '/products/seeds_tomato.png',
    rating: 4.6,
    reviews_count: 876,
    stock: 130,
    brand: 'Namdhari',
    dosage: '100g seed per acre',
    composition: 'Solanum melongena F1 Vajra',
    crops: ['Brinjal'],
    isOrganic: false,
    tags: ['brinjal', 'eggplant', 'F1-hybrid', 'vegetable'],
    aiImagePrompt: 'Brinjal eggplant seeds 10g purple-themed seed packet with shiny purple brinjal illustration, white background, ecommerce product photography',
  },
  {
    id: 'seed-veg-004',
    name: 'Okra Rashmi F1 Hybrid — 500g',
    description: 'High-yielding Bhindi hybrid. Light green, straight tender pods. First harvest in 40–45 days. Tolerant to YVMV (Yellow Vein Mosaic Virus). Harvest 3× per week. Good for fresh market and export.',
    shortDesc: 'YVMV-tolerant okra — first harvest in 40 days',
    category: 'seeds',
    subCategory: 'vegetable',
    price: 399,
    mrp: 549,
    discount: 27,
    image_url: '/products/seeds_tomato.png',
    rating: 4.7,
    reviews_count: 1234,
    stock: 190,
    brand: 'East-West',
    dosage: '3–4 kg seed per acre',
    composition: 'Abelmoschus esculentus F1 Rashmi',
    crops: ['Okra / Bhindi'],
    isOrganic: false,
    tags: ['okra', 'bhindi', 'YVMV-tolerant', 'vegetable'],
    aiImagePrompt: 'Okra Bhindi seeds 500g packet with fresh green okra photography, East-West brand, white background, agricultural product ecommerce photo',
  },
  {
    id: 'seed-veg-005',
    name: 'Onion Arka Kalyan — 500g',
    description: 'Medium-early Rabi onion variety. Deep red color, pungent. Globular to flat-globular shape. Maturity: 110–120 days. Yield: 20–25 t/ha. Excellent storage life (4–6 months). Most popular onion in Maharashtra.',
    shortDesc: 'Best-selling red onion — 4–6 month storage life',
    category: 'seeds',
    subCategory: 'vegetable',
    price: 649,
    mrp: 850,
    discount: 24,
    image_url: '/products/seeds_tomato.png',
    rating: 4.7,
    reviews_count: 1890,
    stock: 210,
    brand: 'IIHR',
    dosage: '3–4 kg seed per acre (nursery)',
    composition: 'Allium cepa Arka Kalyan, germination >85%',
    crops: ['Onion'],
    badge: '🧅 #1 Variety',
    isOrganic: false,
    tags: ['onion', 'rabi', 'red-onion', 'storage'],
    aiImagePrompt: 'Onion Arka Kalyan seeds 500g packet with red onion bulb photography, IIHR brand label, white background, ecommerce product photo',
  },
];

export const FRUIT_PLANTATION_SEEDS: ExtendedProduct[] = [
  {
    id: 'seed-fr-001',
    name: 'Watermelon Sugarbaby F1 — 50g',
    description: 'Compact Sugarbaby watermelon with 8–10 kg fruits. Deep red, sweet flesh (Brix 12–13%). Matures in 75–80 days. Round fruit with dark green rind. Ideal for small farms and markets. Disease tolerant, excellent shelf life.',
    shortDesc: 'Sweet red watermelon — Brix 12–13%, compact vine',
    category: 'seeds',
    subCategory: 'fruit-plantation',
    price: 499,
    mrp: 699,
    discount: 29,
    image_url: '/products/seeds_tomato.png',
    rating: 4.7,
    reviews_count: 987,
    stock: 140,
    brand: 'Known-You',
    dosage: '300–500g seed per acre',
    composition: 'Citrullus lanatus F1 Sugarbaby',
    crops: ['Watermelon'],
    isOrganic: false,
    tags: ['watermelon', 'sugarbaby', 'summer', 'fruit'],
    aiImagePrompt: 'Watermelon Sugarbaby seeds 50g premium foil packet with cut watermelon photography showing red flesh, white background, ecommerce product photo',
  },
  {
    id: 'seed-fr-002',
    name: 'Papaya CO-7 Tissue Culture Sapling',
    description: 'Taiwan Red Lady-type papaya tissue culture sapling. Early bearing (9–10 months). Regular hermaphrodite plants (100%). Excellent disease resistance (PRSV tolerant). Yield: 80–100 fruits per tree per year. Ideal for commercial papaya farming.',
    shortDesc: 'PRSV-tolerant papaya — 80–100 fruits/tree/year',
    category: 'seeds',
    subCategory: 'fruit-plantation',
    price: 45,
    mrp: 60,
    discount: 25,
    image_url: '/products/seeds_tomato.png',
    rating: 4.8,
    reviews_count: 654,
    stock: 500,
    brand: 'TNAU',
    dosage: '1 sapling per pit (2.5m × 2.5m spacing)',
    composition: 'Carica papaya CO-7, tissue cultured',
    crops: ['Papaya'],
    badge: '🌿 Tissue Culture',
    isOrganic: false,
    tags: ['papaya', 'sapling', 'tissue-culture', 'PRSV-tolerant'],
    aiImagePrompt: 'Papaya CO-7 tissue culture sapling small plant in grow bag, nursery packaging, professional photography, white background',
  },
];

export const FLOWER_HERBAL_SEEDS: ExtendedProduct[] = [
  {
    id: 'seed-flh-001',
    name: 'Marigold African Giant Seeds — 50g',
    description: 'African marigold with large double flowers. Bright orange-yellow colors. Repels soil nematodes when intercropped. Flowering in 60–70 days from transplanting. Used in garlands, landscaping, and essential oil extraction.',
    shortDesc: 'Giant marigold — repels nematodes, traditional & commercial use',
    category: 'seeds',
    subCategory: 'flower-herbal',
    price: 149,
    mrp: 199,
    discount: 25,
    image_url: '/products/seeds_tomato.png',
    rating: 4.6,
    reviews_count: 1234,
    stock: 280,
    brand: 'Sakata',
    dosage: '1 kg seed per acre (nursery)',
    composition: 'Tagetes erecta var. African Giant',
    crops: ['Marigold'],
    isOrganic: false,
    tags: ['marigold', 'flower', 'nematode-repellent', 'garland'],
    aiImagePrompt: 'Marigold flower seeds 50g packet with bright orange marigold flower photography, Sakata brand, white background, ecommerce product photo',
  },
  {
    id: 'seed-flh-002',
    name: 'Moringa Drumstick Seeds — 500g',
    description: 'PKM-1 drumstick variety. High yielding, perennial tree crop. Nutritionally dense pods and leaves. Drought tolerant. First harvest in 6 months from planting. Continues for 10+ years. Used in food, nutraceuticals, and export market.',
    shortDesc: 'PKM-1 drumstick — first harvest in 6 months, 10+ years lifespan',
    category: 'seeds',
    subCategory: 'flower-herbal',
    price: 299,
    mrp: 399,
    discount: 25,
    image_url: '/products/seeds_tomato.png',
    rating: 4.7,
    reviews_count: 876,
    stock: 165,
    brand: 'TNAU',
    dosage: '3 seeds per pit, thin to 1 plant',
    composition: 'Moringa oleifera PKM-1',
    crops: ['Moringa / Drumstick'],
    isOrganic: true,
    tags: ['moringa', 'drumstick', 'superfood', 'perennial'],
    aiImagePrompt: 'Moringa drumstick seeds 500g packet with moringa pod and leaf illustration, natural green label, white background, ecommerce photography',
  },
  {
    id: 'seed-flh-003',
    name: 'Ashwagandha (Withania somnifera) Seeds — 100g',
    description: 'Certified Ashwagandha seeds for medicinal crop production. 1.5–2% withanolide content (pharmaceutical grade). Drought tolerant, rain-fed cultivation possible. Matures in 150–180 days. Growing demand from pharma and nutraceutical industry.',
    shortDesc: 'Pharma-grade Ashwagandha — high withanolide content',
    category: 'seeds',
    subCategory: 'flower-herbal',
    price: 249,
    mrp: 349,
    discount: 29,
    image_url: '/products/seeds_tomato.png',
    rating: 4.8,
    reviews_count: 543,
    stock: 95,
    brand: 'CIMAP',
    dosage: '5 kg seed per hectare (broadcast)',
    composition: 'Withania somnifera certified seeds',
    crops: ['Ashwagandha'],
    badge: '💊 Medicinal',
    isOrganic: true,
    tags: ['ashwagandha', 'medicinal', 'herbal', 'ayurvedic'],
    aiImagePrompt: 'Ashwagandha seeds 100g premium packet with traditional Indian ayurvedic design, herb illustration, white background, ecommerce product photography',
  },
  {
    id: 'seed-flh-004',
    name: 'Tulsi (Holy Basil) Seeds — 50g',
    description: 'Ocimum sanctum — sacred Tulsi seeds. High eugenol content for medicinal use. Aromatic, bushy plant. Used in herbal tea, ayurvedic medicines, and essential oil. Easy to grow in pots and fields. Year-round cultivation.',
    shortDesc: 'Sacred Tulsi — high eugenol, medicinal & spiritual use',
    category: 'seeds',
    subCategory: 'flower-herbal',
    price: 99,
    mrp: 149,
    discount: 34,
    image_url: '/products/seeds_tomato.png',
    rating: 4.7,
    reviews_count: 987,
    stock: 200,
    brand: 'Organic India',
    dosage: '0.5 kg per acre or direct sowing in pots',
    composition: 'Ocimum sanctum (Rama Tulsi)',
    crops: ['Tulsi'],
    isOrganic: true,
    tags: ['tulsi', 'holy-basil', 'medicinal', 'ayurvedic'],
    aiImagePrompt: 'Tulsi holy basil seeds 50g green packet with tulsi plant and Om symbol illustration, Organic India brand, white background, ecommerce photography',
  },
];

// ─── PROTEIN CUTS / LIVESTOCK ─────────────────────────────────────────────────

export const LIVESTOCK_NUTRITION: ExtendedProduct[] = [
  {
    id: 'live-001',
    name: 'High Protein Cattle Feed Supplement — 25kg',
    description: 'Bypass protein supplement for dairy cattle. Increases milk production by 15–20%. Protected from rumen degradation — directly absorbed in intestine. Improves body condition score. Suitable for high-yielding crossbred cows and buffaloes.',
    shortDesc: '15–20% more milk — bypass protein for dairy cattle',
    category: 'protein-cuts',
    subCategory: 'livestock-nutrition',
    price: 1499,
    mrp: 1899,
    discount: 21,
    image_url: '/products/fertilizer_npk.png',
    rating: 4.7,
    reviews_count: 432,
    stock: 120,
    brand: 'Amul AgroVet',
    dosage: '250–500g per animal per day',
    composition: 'Bypass protein 55%, Metabolizable energy',
    crops: ['Dairy Cattle', 'Buffalo'],
    badge: '🐄 Dairy Boost',
    isOrganic: false,
    tags: ['livestock', 'cattle-feed', 'dairy', 'milk-production'],
    aiImagePrompt: 'Cattle feed protein supplement 25kg bag with dairy cow illustration, Amul brand style packaging, white background, agricultural product photography',
  },
  {
    id: 'live-002',
    name: 'Poultry Feed Supplement (Broiler) — 25kg',
    description: 'High-energy broiler feed supplement. Optimum amino acid profile for fast growth. Improves FCR (Feed Conversion Ratio) by 10–15%. Enriched with vitamins A, D3, E, K. Coccidiostat included for gut health. For 0–3 week broiler chicks.',
    shortDesc: 'Fast broiler growth — 10–15% better FCR',
    category: 'protein-cuts',
    subCategory: 'livestock-nutrition',
    price: 1299,
    mrp: 1599,
    discount: 19,
    image_url: '/products/fertilizer_npk.png',
    rating: 4.6,
    reviews_count: 287,
    stock: 85,
    brand: 'Venky\'s',
    dosage: 'Ad libitum (free access), starter phase 0–3 weeks',
    composition: 'Protein 22%, Fat 4%, Fiber 4%, Ash 7%',
    crops: ['Broiler Poultry'],
    isOrganic: false,
    tags: ['poultry', 'broiler', 'feed', 'livestock'],
    aiImagePrompt: 'Broiler poultry feed supplement 25kg bag with chicken illustration, Venky\'s brand style, white background, product photography',
  },
  {
    id: 'live-003',
    name: 'Organic Feed Supplement (Azolla) — 5kg Dry',
    description: 'Dried Azolla — high-protein aquatic fern. Nitrogen-fixing, naturally rich in amino acids. Protein content 25–30% dry weight. Used as fodder supplement for cattle, poultry, and fish. Reduces feed cost by 20%. Grows rapidly in water bodies.',
    shortDesc: 'Azolla protein supplement — cuts feed cost by 20%',
    category: 'protein-cuts',
    subCategory: 'organic-feed',
    price: 349,
    mrp: 499,
    discount: 30,
    image_url: '/products/neem_oil.png',
    rating: 4.5,
    reviews_count: 187,
    stock: 65,
    brand: 'AgroOrganic',
    dosage: '10–15% of total diet for poultry; 1–2 kg/day cattle',
    composition: 'Azolla dry powder, protein 25–30%',
    crops: ['Poultry', 'Dairy Cattle', 'Fish'],
    isOrganic: true,
    tags: ['azolla', 'organic-feed', 'sustainable', 'protein'],
    aiImagePrompt: 'Azolla organic feed supplement 5kg green eco-packaging, natural green leaf design, white background, agricultural product photography',
  },
  {
    id: 'live-004',
    name: 'Animal Health Mineral Mixture — 5kg',
    description: 'Complete mineral and vitamin premix for livestock. Prevents mineral deficiency diseases — milk fever, grass tetany, rickets. Improves reproductive efficiency and conception rate. Boosts immunity and disease resistance. For cattle, buffalo, sheep, goat.',
    shortDesc: 'Prevent mineral deficiency — boosts fertility & immunity',
    category: 'protein-cuts',
    subCategory: 'animal-health',
    price: 499,
    mrp: 699,
    discount: 29,
    image_url: '/products/fungicide_copper.png',
    rating: 4.6,
    reviews_count: 345,
    stock: 95,
    brand: 'Godrej AgroVet',
    dosage: '50–100g per animal per day mixed in feed',
    composition: 'Ca 25%, P 15%, Mg 2%, Zn 0.5%, + vitamins A, D3, E',
    crops: ['Cattle', 'Buffalo', 'Sheep', 'Goat'],
    isOrganic: false,
    tags: ['mineral-mixture', 'livestock-health', 'cattle', 'supplement'],
    aiImagePrompt: 'Animal mineral mixture 5kg premium packaging with cattle illustration, Godrej AgroVet style, white background, ecommerce product photography',
  },
];

// ─── COMBINED EXPORTS ─────────────────────────────────────────────────────────

export const ALL_FERTILIZERS: ExtendedProduct[] = [
  ...ORGANIC_FERTILIZERS,
  ...CHEMICAL_FERTILIZERS,
  ...BIO_FERTILIZERS,
  ...MICRONUTRIENT_FERTILIZERS,
  ...NANO_FERTILIZERS,
  ...PGR_FERTILIZERS,
];

export const ALL_SEEDS: ExtendedProduct[] = [
  ...FIELD_CROP_SEEDS,
  ...VEGETABLE_SEEDS,
  ...FRUIT_PLANTATION_SEEDS,
  ...FLOWER_HERBAL_SEEDS,
];

export const ALL_PROTEIN_CUTS: ExtendedProduct[] = [
  ...LIVESTOCK_NUTRITION,
];

export const ALL_PRODUCTS: ExtendedProduct[] = [
  ...ALL_FERTILIZERS,
  ...ALL_SEEDS,
  ...ALL_PROTEIN_CUTS,
];

export const FERTILIZER_SUBCATEGORIES = [
  { id: 'all', label: 'All Fertilizers', emoji: '🧪', count: ALL_FERTILIZERS.length },
  { id: 'organic', label: 'Organic Fertilizers', emoji: '🌿', count: ORGANIC_FERTILIZERS.length },
  { id: 'chemical', label: 'Chemical Fertilizers', emoji: '⚗️', count: CHEMICAL_FERTILIZERS.length },
  { id: 'biofertilizer', label: 'Bio Fertilizers', emoji: '🦠', count: BIO_FERTILIZERS.length },
  { id: 'micronutrient', label: 'Micronutrient', emoji: '🔬', count: MICRONUTRIENT_FERTILIZERS.length },
  { id: 'nano', label: 'Nano Fertilizers', emoji: '🔭', count: NANO_FERTILIZERS.length },
  { id: 'pgr', label: 'Plant Growth Promoters', emoji: '📈', count: PGR_FERTILIZERS.length },
];

export const SEED_SUBCATEGORIES = [
  { id: 'all', label: 'All Seeds', emoji: '🌱', count: ALL_SEEDS.length },
  { id: 'field-crops', label: 'Field Crops', emoji: '🌾', count: FIELD_CROP_SEEDS.length },
  { id: 'vegetable', label: 'Vegetables', emoji: '🥦', count: VEGETABLE_SEEDS.length },
  { id: 'fruit-plantation', label: 'Fruits & Plantation', emoji: '🍅', count: FRUIT_PLANTATION_SEEDS.length },
  { id: 'flower-herbal', label: 'Flowers & Herbal', emoji: '🌸', count: FLOWER_HERBAL_SEEDS.length },
];
