// lib/products-data.ts
// ─── IGO CropCare — Real Product Catalog ─────────────────────────────────────
// Brand: Chemica Fertilizers & Allied Products
// NOTE: Image URLs use Unsplash placeholders.
// To use your own images: copy them to /public/products/chemica/
// then replace image_url values with '/products/chemica/filename.png'

export interface ExtendedProduct {
  id: string;
  name: string;
  description: string;
  shortDesc: string;
  category: string;
  subCategory: string;
  price: number;
  mrp: number;
  discount: number;
  image_url: string;
  rating: number;
  reviews_count: number;
  stock: number;
  brand: string;
  dosage: string;
  composition: string;
  crops: string[];
  badge?: string;
  isOrganic: boolean;
  tags: string[];
  aiImagePrompt: string;
}

// ─── CHEMICAL FERTILIZERS ────────────────────────────────────────────────────

export const CHEMICAL_FERTILIZERS: ExtendedProduct[] = [
  {
    id: 'chem-fert-001',
    name: 'Chemica NPK 19:19:19 Water Soluble Fertilizer',
    description: 'Fully water-soluble balanced NPK fertilizer with equal ratios of Nitrogen, Phosphorus and Potassium. Ideal for all crops at vegetative stage. Quick absorption via foliar spray or drip irrigation. Boosts green growth, root development and early flowering. Contains chelated micronutrients for enhanced uptake.',
    shortDesc: 'Balanced NPK for all crops — fast-acting water-soluble formula',
    category: 'fertilizers',
    subCategory: 'chemical',
    price: 349,
    mrp: 480,
    discount: 27,
    image_url: 'https://images.unsplash.com/photo-1574943320219-553eb213f72d?w=600&h=600&fit=crop',
    rating: 4.8,
    reviews_count: 2341,
    stock: 500,
    brand: 'Chemica',
    dosage: '2–3g per litre of water via foliar spray or drip irrigation',
    composition: 'Nitrogen (N) 19% + Phosphorus (P₂O₅) 19% + Potassium (K₂O) 19%',
    crops: ['Tomato', 'Chilli', 'Cotton', 'Paddy', 'Wheat', 'Vegetables', 'Fruits'],
    badge: '⭐ Best Seller',
    isOrganic: false,
    tags: ['npk', 'water-soluble', 'fertilizer', 'balanced'],
    aiImagePrompt: 'Chemica NPK 19:19:19 blue white fertilizer bag 1kg professional product photography',
  },
  {
    id: 'chem-fert-002',
    name: 'Chemica DAP 50kg (Di-Ammonium Phosphate)',
    description: 'Premium quality Di-Ammonium Phosphate — the most widely used phosphatic fertilizer in India. High in Phosphorus and Nitrogen. Promotes strong root development, early plant establishment and flowering. Suitable as basal dose for all field and horticultural crops. Govt. MRP product.',
    shortDesc: 'Most-trusted basal phosphatic fertilizer for all field crops',
    category: 'fertilizers',
    subCategory: 'chemical',
    price: 1350,
    mrp: 1500,
    discount: 10,
    image_url: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600&h=600&fit=crop',
    rating: 4.7,
    reviews_count: 1892,
    stock: 200,
    brand: 'Chemica',
    dosage: '50–60 kg per acre as basal dose before sowing',
    composition: 'Nitrogen (N) 18% + Phosphorus (P₂O₅) 46%',
    crops: ['Paddy', 'Wheat', 'Cotton', 'Sugarcane', 'Maize', 'Soybean', 'All Crops'],
    badge: '🌾 Most Popular',
    isOrganic: false,
    tags: ['dap', 'phosphorus', 'basal', 'fertilizer'],
    aiImagePrompt: 'Chemica DAP fertilizer 50kg grey bag Indian agriculture product',
  },
  {
    id: 'chem-fert-003',
    name: 'Chemica Urea 45kg (Neem Coated Granular)',
    description: 'Neem-coated granular urea providing slow-release nitrogen for sustained vegetative growth. Neem coating inhibits nitrification reducing nitrogen losses by 10–15%. Enhances leaf greenness, increases yield and supports tillering in cereals. Government MRP product.',
    shortDesc: 'Neem-coated urea — slow-release N, reduces losses by 15%',
    category: 'fertilizers',
    subCategory: 'chemical',
    price: 267,
    mrp: 267,
    discount: 0,
    image_url: 'https://images.unsplash.com/photo-1500651230702-0e2d8a49d4ad?w=600&h=600&fit=crop',
    rating: 4.6,
    reviews_count: 3210,
    stock: 800,
    brand: 'Chemica',
    dosage: '25–30 kg per acre as top dressing at 25–30 DAS',
    composition: 'Nitrogen (N) 46% as Urea + Neem oil coating 0.5%',
    crops: ['Paddy', 'Wheat', 'Sugarcane', 'Cotton', 'Maize', 'All Crops'],
    isOrganic: false,
    tags: ['urea', 'nitrogen', 'neem-coated', 'granular'],
    aiImagePrompt: 'Chemica Neem Coated Urea 45kg white granular fertilizer bag',
  },
  {
    id: 'chem-fert-004',
    name: 'Chemica NPK 12:32:16 Crop Booster',
    description: 'High-phosphorus NPK blend specially formulated for root zone development and flowering stage. Promotes early and uniform flowering, fruit set and grain formation. Widely used in cotton, chilli and oilseeds at transplanting and early growth stage.',
    shortDesc: 'High-P NPK for transplanting, root development and flowering',
    category: 'fertilizers',
    subCategory: 'chemical',
    price: 580,
    mrp: 750,
    discount: 23,
    image_url: 'https://images.unsplash.com/photo-1464226184081-280282069fda?w=600&h=600&fit=crop',
    rating: 4.7,
    reviews_count: 876,
    stock: 350,
    brand: 'Chemica',
    dosage: '3–4g per litre via drip or foliar spray at transplanting',
    composition: 'Nitrogen (N) 12% + Phosphorus (P₂O₅) 32% + Potassium (K₂O) 16%',
    crops: ['Cotton', 'Chilli', 'Groundnut', 'Soybean', 'Sunflower', 'Tomato'],
    isOrganic: false,
    tags: ['npk', 'high-phosphorus', 'transplanting', 'flowering'],
    aiImagePrompt: 'Chemica NPK 12:32:16 yellow fertilizer bag agricultural product',
  },
  {
    id: 'chem-fert-005',
    name: 'Chemica MOP 50kg (Muriate of Potash)',
    description: 'High-grade Muriate of Potash providing concentrated Potassium for fruit quality, drought resistance and disease tolerance. Essential at fruiting and grain-filling stage. Improves shelf life, fruit firmness and crop maturity uniformity.',
    shortDesc: 'Potash fertilizer for better fruit quality and stress tolerance',
    category: 'fertilizers',
    subCategory: 'chemical',
    price: 1700,
    mrp: 1900,
    discount: 11,
    image_url: 'https://images.unsplash.com/photo-1592841200221-a6898f307baa?w=600&h=600&fit=crop',
    rating: 4.6,
    reviews_count: 654,
    stock: 180,
    brand: 'Chemica',
    dosage: '25–30 kg per acre at fruit development stage',
    composition: 'Potassium (K₂O) 60% as Muriate of Potash',
    crops: ['Tomato', 'Potato', 'Onion', 'Sugarcane', 'Banana', 'Grapes'],
    isOrganic: false,
    tags: ['mop', 'potash', 'potassium', 'fruit-quality'],
    aiImagePrompt: 'Chemica MOP potash 50kg fertilizer bag',
  },
  {
    id: 'chem-fert-006',
    name: 'Chemica Calcium Nitrate 1kg (Foliar Grade)',
    description: 'Water-soluble Calcium Nitrate providing both Calcium and Nitrogen in foliar-available form. Prevents tip burn, blossom end rot and fruit cracking. Strengthens cell walls, improves fruit firmness and post-harvest quality. Essential for high-value vegetables and fruits.',
    shortDesc: 'Prevents blossom end rot and fruit cracking — Calcium + N foliar',
    category: 'fertilizers',
    subCategory: 'micronutrient',
    price: 220,
    mrp: 299,
    discount: 26,
    image_url: 'https://images.unsplash.com/photo-1574943320219-553eb213f72d?w=600&h=600&fit=crop',
    rating: 4.8,
    reviews_count: 1120,
    stock: 450,
    brand: 'Chemica',
    dosage: '2–3g per litre foliar spray at fruit development',
    composition: 'Calcium (Ca) 18.8% + Nitrogen (N) 15.5% as Calcium Nitrate',
    crops: ['Tomato', 'Capsicum', 'Cucumber', 'Apple', 'Grapes', 'Onion'],
    badge: '🔬 Specialty',
    isOrganic: false,
    tags: ['calcium', 'nitrate', 'foliar', 'fruit-quality'],
    aiImagePrompt: 'Chemica Calcium Nitrate 1kg white crystalline fertilizer bag',
  },
];

// ─── ORGANIC FERTILIZERS ─────────────────────────────────────────────────────

export const ORGANIC_FERTILIZERS: ExtendedProduct[] = [
  {
    id: 'chem-org-001',
    name: 'Chemica Vermicompost Premium 5kg',
    description: 'Enriched vermicompost made from earthworm castings. Rich in humus, beneficial microbes, enzymes and plant growth hormones. Improves soil structure, water retention and aeration. Enhances root development and microbial diversity. NPOP certified organic.',
    shortDesc: 'Premium earthworm-cast compost — soil health and root growth',
    category: 'fertilizers',
    subCategory: 'organic',
    price: 299,
    mrp: 399,
    discount: 25,
    image_url: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600&h=600&fit=crop',
    rating: 4.9,
    reviews_count: 2190,
    stock: 600,
    brand: 'Chemica',
    dosage: '2–3 kg per plant or 1–2 tonnes per acre',
    composition: 'Vermicompost (Earthworm castings) 100% — Organic Matter >25%',
    crops: ['All Crops', 'Vegetables', 'Fruits', 'Flowers', 'Nursery'],
    badge: '🌿 NPOP Certified',
    isOrganic: true,
    tags: ['organic', 'vermicompost', 'soil-health', 'certified'],
    aiImagePrompt: 'Chemica Vermicompost 5kg brown kraft paper bag certified organic fertilizer',
  },
  {
    id: 'chem-org-002',
    name: 'Chemica Neem Cake Fertilizer 10kg',
    description: 'Organic neem seed cake — dual-action natural pesticide and fertilizer. Controls soil-borne pests, nematodes and white grubs. Slow-release nitrogen source. Inhibits nitrification reducing nitrogen loss. Improves soil physical properties.',
    shortDesc: 'Neem cake — controls soil pests + slow-release N',
    category: 'fertilizers',
    subCategory: 'organic',
    price: 350,
    mrp: 450,
    discount: 22,
    image_url: 'https://images.unsplash.com/photo-1500651230702-0e2d8a49d4ad?w=600&h=600&fit=crop',
    rating: 4.7,
    reviews_count: 987,
    stock: 400,
    brand: 'Chemica',
    dosage: '50–100 kg per acre as basal application',
    composition: 'Neem Seed Cake 100% — N: 5–6%, P: 1%, K: 1.5%',
    crops: ['Paddy', 'Sugarcane', 'Vegetables', 'Cotton', 'Groundnut'],
    badge: '🌿 Organic',
    isOrganic: true,
    tags: ['neem', 'organic', 'soil-pest', 'nitrogen'],
    aiImagePrompt: 'Chemica Neem Cake 10kg organic fertilizer bag agricultural product',
  },
  {
    id: 'chem-org-003',
    name: 'Chemica Seaweed Extract Liquid 1L',
    description: 'Cold-processed seaweed extract from Ascophyllum nodosum. Rich in natural cytokinins, auxins, betaines and alginic acid. Improves seed germination, tillering, flowering and fruit set. Enhances stress tolerance against drought and salinity.',
    shortDesc: 'Seaweed growth promoter — germination, flowering, drought tolerance',
    category: 'fertilizers',
    subCategory: 'organic',
    price: 450,
    mrp: 599,
    discount: 25,
    image_url: 'https://images.unsplash.com/photo-1545259741-2ea3ebf61fa3?w=600&h=600&fit=crop',
    rating: 4.8,
    reviews_count: 765,
    stock: 300,
    brand: 'Chemica',
    dosage: '2–3 ml per litre foliar; 5 ml per litre soil drench',
    composition: 'Seaweed Extract (Ascophyllum nodosum) 15% — Alginic acid, Cytokinins',
    crops: ['All Crops', 'Fruits', 'Vegetables', 'Floriculture'],
    badge: '🌊 Premium',
    isOrganic: true,
    tags: ['seaweed', 'organic', 'growth-promoter', 'stress-tolerance'],
    aiImagePrompt: 'Chemica Seaweed Extract 1 litre green bottle organic bio-stimulant',
  },
  {
    id: 'chem-bio-003',
    name: 'Chemica Pure Neem Oil 1L (10000 PPM Azadirachtin)',
    description: 'Cold-pressed neem oil with 10,000 PPM Azadirachtin content. Controls 300+ pest species including aphids, whiteflies, thrips, spider mites and mealybugs. Acts as anti-feedant, growth regulator and repellent. 100% natural, biodegradable. Safe for pollinators when applied in evening.',
    shortDesc: '10,000 PPM neem oil — controls 300+ pests organically',
    category: 'organic',
    subCategory: 'bio-pesticide',
    price: 399,
    mrp: 550,
    discount: 27,
    image_url: 'https://images.unsplash.com/photo-1545259741-2ea3ebf61fa3?w=600&h=600&fit=crop',
    rating: 4.8,
    reviews_count: 1876,
    stock: 600,
    brand: 'Chemica',
    dosage: '5 ml per litre + 1 ml emulsifier; spray on both leaf surfaces',
    composition: 'Cold-pressed Neem Oil — Azadirachtin 10,000 PPM minimum',
    crops: ['Tomato', 'Chilli', 'Brinjal', 'Cotton', 'Okra', 'Vegetables', 'Fruits'],
    badge: '🌿 100% Organic',
    isOrganic: true,
    tags: ['neem-oil', 'organic', 'bio-pesticide', 'azadirachtin'],
    aiImagePrompt: 'Chemica Pure Neem Oil 1 litre amber bottle organic pest control',
  },
  {
    id: 'chem-bio-001',
    name: 'Chemica Trichoderma viride 1kg (Bio-Fungicide)',
    description: 'Trichoderma viride biological fungicide — controls soil-borne fungal diseases including Pythium, Fusarium, Rhizoctonia and Sclerotinia. Promotes root growth and colonization. Compatible with chemical fungicides. Safe for soil health and beneficial microbes.',
    shortDesc: 'Bio-fungicide for root diseases — soil drench or seed treatment',
    category: 'organic',
    subCategory: 'bio-fungicide',
    price: 280,
    mrp: 350,
    discount: 20,
    image_url: 'https://images.unsplash.com/photo-1600565193348-f74bd3c7ccdf?w=600&h=600&fit=crop',
    rating: 4.7,
    reviews_count: 543,
    stock: 350,
    brand: 'Chemica',
    dosage: '2.5 kg per acre soil application; 5g per kg seed treatment',
    composition: 'Trichoderma viride 2×10⁶ CFU/g minimum',
    crops: ['Tomato', 'Chilli', 'Cotton', 'Paddy', 'Wheat', 'Vegetables'],
    badge: '🦠 Bio-Control',
    isOrganic: true,
    tags: ['bio-fungicide', 'trichoderma', 'root-disease', 'organic'],
    aiImagePrompt: 'Chemica Trichoderma bio fungicide 1kg brown bag bio-control',
  },
  {
    id: 'chem-bio-002',
    name: 'Chemica PSB Biofertilizer 1kg',
    description: 'Bacillus megaterium-based phosphate solubilising bacteria. Converts insoluble soil phosphorus to plant-available form. Reduces phosphatic fertilizer requirement by 25–30%. Improves plant growth, root development and soil phosphorus availability.',
    shortDesc: 'PSB biofertilizer — unlocks soil phosphorus, reduces DAP use by 25%',
    category: 'organic',
    subCategory: 'biofertilizer',
    price: 180,
    mrp: 220,
    discount: 18,
    image_url: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600&h=600&fit=crop',
    rating: 4.6,
    reviews_count: 432,
    stock: 500,
    brand: 'Chemica',
    dosage: '2.5 kg per acre soil or 200g per acre seed treatment',
    composition: 'Bacillus megaterium 2×10⁷ CFU/g minimum',
    crops: ['Wheat', 'Paddy', 'Maize', 'Pulses', 'Oilseeds', 'Vegetables'],
    isOrganic: true,
    tags: ['psb', 'biofertilizer', 'phosphorus', 'bacteria'],
    aiImagePrompt: 'Chemica PSB biofertilizer 1kg packet bio-inoculant agricultural',
  },
];

// ─── INSECTICIDES ─────────────────────────────────────────────────────────────

export const INSECTICIDES: ExtendedProduct[] = [
  {
    id: 'chem-ins-001',
    name: 'Chemica Imidacloprid 17.8% SL',
    description: 'Systemic insecticide from neonicotinoid group. Controls sucking pests including aphids, jassids, whiteflies, thrips and brown plant hoppers. Absorbed through roots and leaves providing systemic protection. Rapid knockdown with residual control up to 15 days.',
    shortDesc: 'Systemic neonicotinoid — fast knockdown for sucking pests',
    category: 'insecticides',
    subCategory: 'neonicotinoid',
    price: 299,
    mrp: 420,
    discount: 29,
    image_url: 'https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?w=600&h=600&fit=crop',
    rating: 4.7,
    reviews_count: 2108,
    stock: 400,
    brand: 'Chemica',
    dosage: '100–150 ml per acre in 200 litres of water',
    composition: 'Imidacloprid 17.8% SL — WHO Class II',
    crops: ['Cotton', 'Paddy', 'Tomato', 'Chilli', 'Sugarcane', 'Vegetables'],
    badge: '⚡ Fast Action',
    isOrganic: false,
    tags: ['imidacloprid', 'systemic', 'sucking-pests', 'neonicotinoid'],
    aiImagePrompt: 'Chemica Imidacloprid 17.8 SL insecticide 500ml bottle',
  },
  {
    id: 'chem-ins-002',
    name: 'Chemica Chlorpyrifos 20% EC',
    description: 'Broad-spectrum organophosphate insecticide with contact, stomach and fumigant action. Controls caterpillars, stem borers, termites, leaf folders, aphids and soil insects. Effective against a wide range of crop pests. Widely used in paddy, cotton and vegetables.',
    shortDesc: 'Broad-spectrum for caterpillars, borers and soil insects',
    category: 'insecticides',
    subCategory: 'organophosphate',
    price: 260,
    mrp: 360,
    discount: 28,
    image_url: 'https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?w=600&h=600&fit=crop',
    rating: 4.5,
    reviews_count: 1456,
    stock: 350,
    brand: 'Chemica',
    dosage: '800 ml – 1 litre per acre in 200 litres of water',
    composition: 'Chlorpyrifos 20% EC — WHO Class II',
    crops: ['Paddy', 'Cotton', 'Maize', 'Sugarcane', 'Vegetables', 'Groundnut'],
    isOrganic: false,
    tags: ['chlorpyrifos', 'organophosphate', 'broad-spectrum', 'borer'],
    aiImagePrompt: 'Chemica Chlorpyrifos 20 EC 1 litre insecticide yellow bottle',
  },
  {
    id: 'chem-ins-003',
    name: 'Chemica Thiamethoxam 25% WG',
    description: 'Second-generation neonicotinoid insecticide with systemic action. Controls major sucking and biting pests including whitefly, jassid, aphid, mealybug and white grub. Soil application provides season-long protection.',
    shortDesc: 'Second-gen systemic — season-long sucking pest control',
    category: 'insecticides',
    subCategory: 'neonicotinoid',
    price: 380,
    mrp: 520,
    discount: 27,
    image_url: 'https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?w=600&h=600&fit=crop',
    rating: 4.8,
    reviews_count: 934,
    stock: 280,
    brand: 'Chemica',
    dosage: '40–60g per acre in 200 litres water',
    composition: 'Thiamethoxam 25% WG — WHO Class II',
    crops: ['Cotton', 'Tomato', 'Chilli', 'Sugarcane', 'Okra', 'Brinjal'],
    badge: '🛡️ Season-Long',
    isOrganic: false,
    tags: ['thiamethoxam', 'systemic', 'neonicotinoid', 'whitefly'],
    aiImagePrompt: 'Chemica Thiamethoxam 25 WG 250g packet blue label insecticide',
  },
  {
    id: 'chem-ins-004',
    name: 'Chemica Spinosad 45% SC',
    description: 'Biological insecticide derived from Saccharopolyspora spinosa bacteria. Controls thrips, leaf miners, bollworm and fruit borer. Selectively toxic to target pests — safe for beneficial insects. Suitable for organic farming and resistance management.',
    shortDesc: 'Bio-derived insecticide — safe for beneficials, controls thrips and bollworm',
    category: 'insecticides',
    subCategory: 'bio-insecticide',
    price: 580,
    mrp: 750,
    discount: 23,
    image_url: 'https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?w=600&h=600&fit=crop',
    rating: 4.9,
    reviews_count: 678,
    stock: 200,
    brand: 'Chemica',
    dosage: '60–80 ml per acre in 200 litres of water',
    composition: 'Spinosad 45% SC — Bio-insecticide (Spinosyn A+D)',
    crops: ['Cotton', 'Chilli', 'Tomato', 'Onion', 'Cabbage', 'Tea'],
    badge: '🌿 Bio-Based',
    isOrganic: true,
    tags: ['spinosad', 'bio-insecticide', 'thrips', 'bollworm'],
    aiImagePrompt: 'Chemica Spinosad 45 SC 100ml amber bottle bio-insecticide',
  },
];

// ─── FUNGICIDES ───────────────────────────────────────────────────────────────

export const FUNGICIDES: ExtendedProduct[] = [
  {
    id: 'chem-fun-001',
    name: 'Chemica Mancozeb 75% WP',
    description: 'Multi-site contact fungicide with preventive and curative action. Controls downy mildew, early blight, late blight, leaf spot and rust. Excellent weatherability and broad crop safety. Low cost-to-benefit ratio. One of the most widely used fungicides in Indian agriculture.',
    shortDesc: 'Multi-site fungicide — prevents blight, mildew, rust on all crops',
    category: 'fungicides',
    subCategory: 'contact',
    price: 280,
    mrp: 370,
    discount: 24,
    image_url: 'https://images.unsplash.com/photo-1592417817098-8f3d6eb19675?w=600&h=600&fit=crop',
    rating: 4.6,
    reviews_count: 3120,
    stock: 600,
    brand: 'Chemica',
    dosage: '600–800g per acre in 200 litres of water',
    composition: 'Mancozeb 75% WP — Multi-site EBDC fungicide',
    crops: ['Tomato', 'Potato', 'Paddy', 'Grapes', 'Chilli', 'Wheat', 'Onion'],
    badge: '🏆 Most Trusted',
    isOrganic: false,
    tags: ['mancozeb', 'fungicide', 'blight', 'contact'],
    aiImagePrompt: 'Chemica Mancozeb 75 WP 1kg yellow fungicide pack',
  },
  {
    id: 'chem-fun-002',
    name: 'Chemica Copper Oxychloride 50% WP',
    description: 'Inorganic contact fungicide and bactericide. Controls downy mildew, blast, die-back, angular leaf spot and bacterial diseases. Safe for use near harvest. Doubles as micronutrient copper supplement. Recommended for certified organic farming programs.',
    shortDesc: 'Copper fungicide + bactericide — safe near harvest, organic-approved',
    category: 'fungicides',
    subCategory: 'contact',
    price: 320,
    mrp: 420,
    discount: 24,
    image_url: 'https://images.unsplash.com/photo-1592417817098-8f3d6eb19675?w=600&h=600&fit=crop',
    rating: 4.7,
    reviews_count: 1876,
    stock: 450,
    brand: 'Chemica',
    dosage: '500–800g per acre in 200 litres of water',
    composition: 'Copper Oxychloride 50% WP (Cu 25% equivalent)',
    crops: ['Tomato', 'Paddy', 'Grapes', 'Citrus', 'Chilli', 'Coffee'],
    badge: '✅ Organic Approved',
    isOrganic: false,
    tags: ['copper', 'fungicide', 'bactericide', 'contact'],
    aiImagePrompt: 'Chemica Copper Oxychloride 50 WP 1kg blue-green fungicide pack',
  },
  {
    id: 'chem-fun-003',
    name: 'Chemica Propiconazole 25% EC',
    description: 'Systemic triazole fungicide with protective, curative and eradicant action. Controls sheath blight in paddy, rust and powdery mildew in wheat, Sigatoka in banana and leaf spot in groundnut. Absorbed rapidly through leaves and translocated upward in the plant.',
    shortDesc: 'Systemic triazole — controls rust, sheath blight and powdery mildew',
    category: 'fungicides',
    subCategory: 'systemic',
    price: 380,
    mrp: 499,
    discount: 24,
    image_url: 'https://images.unsplash.com/photo-1600565193348-f74bd3c7ccdf?w=600&h=600&fit=crop',
    rating: 4.8,
    reviews_count: 1234,
    stock: 320,
    brand: 'Chemica',
    dosage: '200 ml per acre in 200 litres of water',
    composition: 'Propiconazole 25% EC — Triazole group',
    crops: ['Paddy', 'Wheat', 'Banana', 'Groundnut', 'Sorghum', 'Turmeric'],
    isOrganic: false,
    tags: ['propiconazole', 'systemic', 'triazole', 'sheath-blight'],
    aiImagePrompt: 'Chemica Propiconazole 25 EC 500ml systemic fungicide amber bottle',
  },
  {
    id: 'chem-fun-004',
    name: 'Chemica Metalaxyl + Mancozeb 72% WP',
    description: 'Combination fungicide with contact + systemic action. Controls late blight, downy mildew and Pythium root rot. Metalaxyl penetrates into leaves providing curative action while Mancozeb provides broad protective cover.',
    shortDesc: 'Dual-action contact+systemic for late blight and downy mildew',
    category: 'fungicides',
    subCategory: 'combination',
    price: 420,
    mrp: 560,
    discount: 25,
    image_url: 'https://images.unsplash.com/photo-1592417817098-8f3d6eb19675?w=600&h=600&fit=crop',
    rating: 4.9,
    reviews_count: 987,
    stock: 280,
    brand: 'Chemica',
    dosage: '600–800g per acre in 200 litres of water',
    composition: 'Metalaxyl 8% + Mancozeb 64% WP',
    crops: ['Tomato', 'Potato', 'Grapes', 'Chilli', 'Soybean', 'Cucurbits'],
    badge: '🔥 Dual Action',
    isOrganic: false,
    tags: ['metalaxyl', 'mancozeb', 'combination', 'late-blight'],
    aiImagePrompt: 'Chemica Metalaxyl Mancozeb 72 WP 1kg dual-action fungicide',
  },
];

// ─── HERBICIDES ───────────────────────────────────────────────────────────────

export const HERBICIDES: ExtendedProduct[] = [
  {
    id: 'chem-herb-001',
    name: 'Chemica Glyphosate 41% SL',
    description: 'Non-selective systemic post-emergence herbicide. Controls all types of annual and perennial weeds including grasses and broadleaf weeds. Absorbed through foliage and translocated to roots killing the entire plant. Used for land preparation and orchard management.',
    shortDesc: 'Non-selective post-emergence — kills all weeds to the root',
    category: 'herbicides',
    subCategory: 'non-selective',
    price: 280,
    mrp: 380,
    discount: 26,
    image_url: 'https://images.unsplash.com/photo-1464226184081-280282069fda?w=600&h=600&fit=crop',
    rating: 4.5,
    reviews_count: 2341,
    stock: 400,
    brand: 'Chemica',
    dosage: '1.0–1.5 litres per acre in 200 litres post-emergence',
    composition: 'Glyphosate 41% SL (Isopropylamine salt)',
    crops: ['Orchard', 'Plantation', 'Non-crop areas', 'Land preparation'],
    isOrganic: false,
    tags: ['glyphosate', 'herbicide', 'non-selective', 'weed'],
    aiImagePrompt: 'Chemica Glyphosate 41 SL 1 litre herbicide bottle green label',
  },
  {
    id: 'chem-herb-002',
    name: 'Chemica 2,4-D Amine Salt 58% SL',
    description: 'Selective systemic herbicide for control of broadleaf weeds in wheat, paddy, sugarcane and maize. Post-emergence application at 2–3 leaf stage of weeds. Does not affect grass crops when applied correctly. Cost-effective and widely proven.',
    shortDesc: 'Selective broadleaf weed control in wheat, paddy and maize',
    category: 'herbicides',
    subCategory: 'selective',
    price: 180,
    mrp: 240,
    discount: 25,
    image_url: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600&h=600&fit=crop',
    rating: 4.4,
    reviews_count: 1654,
    stock: 500,
    brand: 'Chemica',
    dosage: '500 ml per acre in 200 litres of water at 20–25 DAS',
    composition: '2,4-D Amine Salt 58% SL',
    crops: ['Wheat', 'Paddy', 'Sugarcane', 'Maize', 'Sorghum'],
    isOrganic: false,
    tags: ['2-4-d', 'herbicide', 'broadleaf', 'selective'],
    aiImagePrompt: 'Chemica 2,4-D Amine Salt 1 litre selective herbicide red label',
  },
  {
    id: 'chem-herb-003',
    name: 'Chemica Pendimethalin 30% EC',
    description: 'Pre-emergence selective herbicide controlling annual grasses and broadleaf weeds. Apply immediately after sowing before weed emergence. Forms a weed-barrier layer in soil. Widely used in cotton, soybean, groundnut, onion and direct-seeded paddy.',
    shortDesc: 'Pre-emergence weed barrier for cotton, soybean and vegetables',
    category: 'herbicides',
    subCategory: 'pre-emergence',
    price: 320,
    mrp: 430,
    discount: 26,
    image_url: 'https://images.unsplash.com/photo-1464226184081-280282069fda?w=600&h=600&fit=crop',
    rating: 4.6,
    reviews_count: 876,
    stock: 300,
    brand: 'Chemica',
    dosage: '700 ml – 1 litre per acre before weed emergence',
    composition: 'Pendimethalin 30% EC — Dinitroaniline',
    crops: ['Cotton', 'Soybean', 'Groundnut', 'Onion', 'Paddy (DSR)', 'Maize'],
    isOrganic: false,
    tags: ['pendimethalin', 'pre-emergence', 'herbicide', 'weed-barrier'],
    aiImagePrompt: 'Chemica Pendimethalin 30 EC 1 litre herbicide orange bottle',
  },
];

// ─── SEEDS ────────────────────────────────────────────────────────────────────

export const VEGETABLE_SEEDS: ExtendedProduct[] = [
  {
    id: 'chem-seed-001',
    name: 'Chemica F1 Hybrid Tomato Seeds (High Yield)',
    description: 'Determinate F1 hybrid tomato with 100–120 tonnes per acre potential. Fruit: round, uniform 90–100g, bright red, long shelf life. Resistant to TMV, Fusarium wilt and nematodes. Suitable for fresh market and processing. Best for kharif and rabi seasons.',
    shortDesc: 'High-yield F1 hybrid tomato — TMV resistant, 90–100g fruits',
    category: 'seeds',
    subCategory: 'vegetable',
    price: 899,
    mrp: 1200,
    discount: 25,
    image_url: 'https://images.unsplash.com/photo-1592841200221-a6898f307baa?w=600&h=600&fit=crop',
    rating: 4.8,
    reviews_count: 2341,
    stock: 400,
    brand: 'Chemica',
    dosage: '50–60g seeds per acre; sow 0.5–1 cm deep in nursery',
    composition: 'F1 Hybrid Tomato — Germination: 95%+, Purity: 98%+',
    crops: ['Tomato'],
    badge: '🌱 F1 Hybrid',
    isOrganic: false,
    tags: ['tomato', 'seeds', 'f1-hybrid', 'high-yield'],
    aiImagePrompt: 'Chemica F1 Hybrid Tomato seeds packet 10g professional product photo',
  },
  {
    id: 'chem-seed-002',
    name: 'Chemica F1 Hybrid Chilli Seeds (Hot Long)',
    description: 'Indeterminate F1 hybrid chilli with high pungency and good keeping quality. Fruit length 10–12 cm, dark green turning red. Tolerant to CLCV and Anthracnose. Good for fresh market and dry use. Heavy bearing with multiple flushes.',
    shortDesc: 'Hot long F1 hybrid chilli — CLCV tolerant, high-yielding',
    category: 'seeds',
    subCategory: 'vegetable',
    price: 750,
    mrp: 999,
    discount: 25,
    image_url: 'https://images.unsplash.com/photo-1583119022894-919a68a3d0e3?w=600&h=600&fit=crop',
    rating: 4.7,
    reviews_count: 1543,
    stock: 350,
    brand: 'Chemica',
    dosage: '100–120g seeds per acre in nursery beds',
    composition: 'F1 Hybrid Chilli — Germination: 92%+, Purity: 98%+',
    crops: ['Chilli'],
    badge: '🌶️ High Pungency',
    isOrganic: false,
    tags: ['chilli', 'seeds', 'f1-hybrid', 'virus-tolerant'],
    aiImagePrompt: 'Chemica F1 Hybrid Chilli seeds 5g packet red label product photo',
  },
  {
    id: 'chem-seed-003',
    name: 'Chemica F1 Hybrid Brinjal Seeds (Round Purple)',
    description: 'Round-fruited F1 hybrid brinjal with bright purple glossy fruits. Average fruit weight 180–220g. Tolerant to Phomopsis blight and Little Leaf. High-yielding with good market acceptance.',
    shortDesc: 'Purple round F1 hybrid brinjal — blight tolerant, glossy fruits',
    category: 'seeds',
    subCategory: 'vegetable',
    price: 580,
    mrp: 780,
    discount: 26,
    image_url: 'https://images.unsplash.com/photo-1609501676725-7186f017a4b7?w=600&h=600&fit=crop',
    rating: 4.6,
    reviews_count: 876,
    stock: 300,
    brand: 'Chemica',
    dosage: '200–250g seeds per acre in nursery',
    composition: 'F1 Hybrid Brinjal — Germination: 90%+',
    crops: ['Brinjal'],
    isOrganic: false,
    tags: ['brinjal', 'seeds', 'f1-hybrid', 'round'],
    aiImagePrompt: 'Chemica F1 Hybrid Brinjal seeds packet purple label',
  },
  {
    id: 'chem-seed-004',
    name: 'Chemica F1 Hybrid Okra Seeds (Long Green)',
    description: 'Long-fruited F1 hybrid okra, dark green 12–14 cm. Tolerant to Yellow Vein Mosaic Virus (YVMV). High picking frequency, excellent tenderness. Performs well in kharif season across India.',
    shortDesc: 'YVMV-tolerant F1 hybrid okra — long green, frequent picking',
    category: 'seeds',
    subCategory: 'vegetable',
    price: 320,
    mrp: 420,
    discount: 24,
    image_url: 'https://images.unsplash.com/photo-1464226184081-280282069fda?w=600&h=600&fit=crop',
    rating: 4.7,
    reviews_count: 1123,
    stock: 450,
    brand: 'Chemica',
    dosage: '1.5–2 kg seeds per acre for direct sowing',
    composition: 'F1 Hybrid Okra — Germination: 90%+, Purity: 98%+',
    crops: ['Okra'],
    badge: '🟢 YVMV Tolerant',
    isOrganic: false,
    tags: ['okra', 'seeds', 'f1-hybrid', 'virus-tolerant'],
    aiImagePrompt: 'Chemica F1 Hybrid Okra bhindi seeds 50g packet green label',
  },
];

export const FIELD_CROP_SEEDS: ExtendedProduct[] = [
  {
    id: 'chem-seed-005',
    name: 'Chemica BT Cotton Hybrid Seeds (Bollgard II)',
    description: 'Bollgard II BT hybrid cotton with dual-gene Cry1Ac+Cry2Ab protection against bollworms. High yield potential 25–30 quintals seed cotton per acre. Wide adaptability across cotton belt. Resistant to Pink, Spotted and American Bollworm.',
    shortDesc: 'BT cotton Bollgard II — dual-gene bollworm protection, 25–30 q/acre',
    category: 'seeds',
    subCategory: 'field-crop',
    price: 930,
    mrp: 1100,
    discount: 15,
    image_url: 'https://images.unsplash.com/photo-1599599810694-b5ac4dd64e58?w=600&h=600&fit=crop',
    rating: 4.8,
    reviews_count: 3210,
    stock: 600,
    brand: 'Chemica',
    dosage: '900g (1 packet) per acre — 2 seeds per hill, 90×60 cm',
    composition: 'Bollgard II BT Hybrid Cotton (Cry1Ac + Cry2Ab)',
    crops: ['Cotton'],
    badge: '🏆 Bollgard II',
    isOrganic: false,
    tags: ['cotton', 'bt-seeds', 'bollgard', 'hybrid'],
    aiImagePrompt: 'Chemica BT Cotton Bollgard II 450g seed packet professional photo',
  },
  {
    id: 'chem-seed-006',
    name: 'Chemica Hybrid Paddy Seeds (Short Duration)',
    description: 'Short-duration 105–110 days hybrid paddy. Yield potential 28–35 quintals per acre. Fine grain with excellent cooking quality. Moderate tolerance to blast and bacterial leaf blight. Suitable for irrigated transplanted cultivation.',
    shortDesc: '105–110 day hybrid paddy — 28–35 q/acre, blast tolerant',
    category: 'seeds',
    subCategory: 'field-crop',
    price: 580,
    mrp: 720,
    discount: 19,
    image_url: 'https://images.unsplash.com/photo-1574943320219-553eb213f72d?w=600&h=600&fit=crop',
    rating: 4.7,
    reviews_count: 1876,
    stock: 500,
    brand: 'Chemica',
    dosage: '6–8 kg seeds per acre for nursery transplanting',
    composition: 'Hybrid Paddy Seeds — Germination: 85%+, Purity: 98%+',
    crops: ['Paddy'],
    badge: '🌾 High Yield',
    isOrganic: false,
    tags: ['paddy', 'rice-seeds', 'hybrid', 'short-duration'],
    aiImagePrompt: 'Chemica Hybrid Paddy rice seeds 5kg green bag agricultural',
  },
];

export const FRUIT_PLANTATION_SEEDS: ExtendedProduct[] = [];
export const FLOWER_HERBAL_SEEDS: ExtendedProduct[] = [];
export const LIVESTOCK_NUTRITION: ExtendedProduct[] = [];

// ─── MICRONUTRIENTS ───────────────────────────────────────────────────────────

export const MICRONUTRIENT_PRODUCTS: ExtendedProduct[] = [
  {
    id: 'chem-micro-001',
    name: 'Chemica Boron 20% (Solubor Foliar Grade)',
    description: 'Highly soluble sodium octaborate providing 20% Boron. Essential for pollen germination, fruit set, cell wall formation and sugar translocation. Corrects boron deficiency causing hollow stem in cabbage, tip-burn in cauliflower and poor fruit set.',
    shortDesc: '20% soluble boron — improves fruit set, prevents hollow stem',
    category: 'fertilizers',
    subCategory: 'micronutrient',
    price: 180,
    mrp: 240,
    discount: 25,
    image_url: 'https://images.unsplash.com/photo-1574943320219-553eb213f72d?w=600&h=600&fit=crop',
    rating: 4.7,
    reviews_count: 765,
    stock: 500,
    brand: 'Chemica',
    dosage: '1g per litre foliar spray at flower bud stage',
    composition: 'Boron (B) 20% as Sodium Octaborate',
    crops: ['Cotton', 'Groundnut', 'Sunflower', 'Cabbage', 'Cauliflower', 'Grapes'],
    isOrganic: false,
    tags: ['boron', 'micronutrient', 'fruit-set', 'foliar'],
    aiImagePrompt: 'Chemica Boron Solubor 20% 500g white packet micronutrient fertilizer',
  },
  {
    id: 'chem-micro-002',
    name: 'Chemica Zinc Sulphate 33% (Monohydrate)',
    description: 'Monohydrate zinc sulphate with 33% Zn. Corrects zinc deficiency (khaira disease in paddy, white bud in maize, mottle leaf in citrus). Applied as basal soil or foliar spray. Improves chlorophyll formation and grain filling.',
    shortDesc: '33% zinc — corrects khaira in paddy, white bud in maize',
    category: 'fertilizers',
    subCategory: 'micronutrient',
    price: 220,
    mrp: 290,
    discount: 24,
    image_url: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600&h=600&fit=crop',
    rating: 4.6,
    reviews_count: 1234,
    stock: 600,
    brand: 'Chemica',
    dosage: '10 kg per acre soil; 0.5g per litre foliar',
    composition: 'Zinc (Zn) 33% as Zinc Sulphate Monohydrate',
    crops: ['Paddy', 'Maize', 'Wheat', 'Citrus', 'Cotton', 'Vegetables'],
    isOrganic: false,
    tags: ['zinc', 'micronutrient', 'zinc-sulphate', 'khaira'],
    aiImagePrompt: 'Chemica Zinc Sulphate 33% 1kg white crystalline fertilizer pack',
  },
];

// ─── AGGREGATED EXPORTS ───────────────────────────────────────────────────────

export const ALL_FERTILIZERS: ExtendedProduct[] = [
  ...CHEMICAL_FERTILIZERS,
  ...ORGANIC_FERTILIZERS,
  ...MICRONUTRIENT_PRODUCTS,
];

export const ALL_SEEDS: ExtendedProduct[] = [
  ...VEGETABLE_SEEDS,
  ...FIELD_CROP_SEEDS,
];

export const ALL_CROP_PROTECTION: ExtendedProduct[] = [
  ...INSECTICIDES,
  ...FUNGICIDES,
  ...HERBICIDES,
];

export const ALL_PROTEIN_CUTS: ExtendedProduct[] = [];

export const ALL_PRODUCTS: ExtendedProduct[] = [
  ...ALL_FERTILIZERS,
  ...ALL_SEEDS,
  ...ALL_CROP_PROTECTION,
  ...ORGANIC_FERTILIZERS.filter(p => p.category === 'organic'),
];

// ─── SUBCATEGORY METADATA ─────────────────────────────────────────────────────

export const FERTILIZER_SUBCATEGORIES = [
  { id: 'all', label: 'All Fertilizers', emoji: '🌿', count: ALL_FERTILIZERS.length },
  { id: 'chemical', label: 'Chemical / NPK', emoji: '🧪', count: CHEMICAL_FERTILIZERS.length },
  { id: 'organic', label: 'Organic', emoji: '🌱', count: ORGANIC_FERTILIZERS.length },
  { id: 'micronutrient', label: 'Micronutrients', emoji: '🔬', count: MICRONUTRIENT_PRODUCTS.length },
];

export const SEED_SUBCATEGORIES = [
  { id: 'all', label: 'All Seeds', emoji: '🌱', count: ALL_SEEDS.length },
  { id: 'field-crops', label: 'Field Crops', emoji: '🌾', count: FIELD_CROP_SEEDS.length },
  { id: 'vegetable', label: 'Vegetables', emoji: '🥦', count: VEGETABLE_SEEDS.length },
  { id: 'fruit-plantation', label: 'Fruits & Plantation', emoji: '🍅', count: 0 },
  { id: 'flower-herbal', label: 'Flowers & Herbal', emoji: '🌸', count: 0 },
];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                